preds = \
{'Akron': {'Alabama': '37%',
  'Arizona': '19%',
  'Arkansas': '28%',
  'Auburn': '27%',
  'Baylor': '22%',
  'Boise St': '21%',
  'Bryant': '55%',
  'Chatt': '31%',
  'Colgate': '49%',
  'Colo St': '26%',
  'Connecticut': '27%',
  'Creighton': '31%',
  'CS Fullerton': '51%',
  'Davidson': '23%',
  'Delaware': '44%',
  'Duke': '25%',
  'Georgia St': '55%',
  'Gonzaga': '16%',
  'Houston': '27%',
  'Illinois': '25%',
  'Indiana': '34%',
  'Iowa': '26%',
  'Iowa St': '32%',
  'Jville St': '52%',
  'Kansas': '22%',
  'Kentucky': '21%',
  'Longwood': '51%',
  'Loyola-Chi': '32%',
  'LSU': '37%',
  'Marquette': '32%',
  'Memphis': '34%',
  'Miami FL': '33%',
  'Michigan': '28%',
  'Michigan St': '30%',
  'Montana St': '54%',
  'Murray St': '32%',
  'N Mex St': '38%',
  'Norfolk St': '65%',
  'N Carolina': '32%',
  'Notre Dame': '31%',
  'Ohio St': '30%',
  'Providence': '26%',
  'Purdue': '21%',
  'Richmond': '35%',
  'Rutgers': '27%',
  'S Dakota St': '40%',
  'San Diego St': '27%',
  'San Fran': '28%',
  'Seton Hall': '35%',
  "St Mary's": '26%',
  "St Peter's": '51%',
  'TAM C. Christi': '60%',
  'TCU': '34%',
  'Tennessee': '23%',
  'Texas': '33%',
  'Texas Tech': '22%',
  'TX Southern': '52%',
  'UAB': '28%',
  'UCLA': '22%',
  'USC': '26%',
  'Vermont': '41%',
  'Villanova': '21%',
  'Virginia Tech': '29%',
  'Wisconsin': '28%',
  'Wright St': '52%',
  'Wyoming': '35%',
  'Yale': '50%'},
 'Alabama': {'Arizona': '40%',
  'Arkansas': '48%',
  'Auburn': '46%',
  'Baylor': '44%',
  'Boise St': '51%',
  'Bryant': '79%',
  'Chatt': '71%',
  'Colgate': '75%',
  'Colo St': '49%',
  'Connecticut': '45%',
  'Creighton': '60%',
  'CS Fullerton': '82%',
  'Davidson': '56%',
  'Delaware': '77%',
  'Duke': '51%',
  'Georgia St': '80%',
  'Gonzaga': '36%',
  'Houston': '51%',
  'Illinois': '43%',
  'Indiana': '70%',
  'Iowa': '47%',
  'Iowa St': '60%',
  'Jville St': '75%',
  'Kansas': '40%',
  'Kentucky': '44%',
  'Longwood': '74%',
  'Loyola-Chi': '60%',
  'LSU': '51%',
  'Marquette': '55%',
  'Memphis': '68%',
  'Miami FL': '68%',
  'Michigan': '48%',
  'Michigan St': '44%',
  'Montana St': '73%',
  'Murray St': '53%',
  'N Mex St': '67%',
  'Norfolk St': '78%',
  'N Carolina': '55%',
  'Notre Dame': '66%',
  'Ohio St': '54%',
  'Providence': '52%',
  'Purdue': '48%',
  'Richmond': '60%',
  'Rutgers': '57%',
  'S Dakota St': '68%',
  'San Diego St': '56%',
  'San Fran': '57%',
  'Seton Hall': '56%',
  "St Mary's": '41%',
  "St Peter's": '77%',
  'TAM C. Christi': '80%',
  'TCU': '61%',
  'Tennessee': '35%',
  'Texas': '52%',
  'Texas Tech': '45%',
  'TX Southern': '81%',
  'UAB': '59%',
  'UCLA': '48%',
  'USC': '55%',
  'Vermont': '62%',
  'Villanova': '36%',
  'Virginia Tech': '59%',
  'Wisconsin': '50%',
  'Wright St': '82%',
  'Wyoming': '71%',
  'Yale': '81%',
  'Akron': '63%'},
 'Arizona': {'Arkansas': '70%',
  'Auburn': '55%',
  'Baylor': '51%',
  'Boise St': '58%',
  'Bryant': '99%',
  'Chatt': '82%',
  'Colgate': '99%',
  'Colo St': '58%',
  'Connecticut': '64%',
  'Creighton': '60%',
  'CS Fullerton': '99%',
  'Davidson': '73%',
  'Delaware': '99%',
  'Duke': '59%',
  'Georgia St': '99%',
  'Gonzaga': '51%',
  'Houston': '62%',
  'Illinois': '62%',
  'Indiana': '77%',
  'Iowa': '83%',
  'Iowa St': '67%',
  'Jville St': '99%',
  'Kansas': '58%',
  'Kentucky': '50%',
  'Longwood': '99%',
  'Loyola-Chi': '83%',
  'LSU': '66%',
  'Marquette': '57%',
  'Memphis': '63%',
  'Miami FL': '85%',
  'Michigan': '62%',
  'Michigan St': '56%',
  'Montana St': '99%',
  'Murray St': '86%',
  'N Mex St': '93%',
  'Norfolk St': '99%',
  'N Carolina': '79%',
  'Notre Dame': '92%',
  'Ohio St': '65%',
  'Providence': '61%',
  'Purdue': '55%',
  'Richmond': '75%',
  'Rutgers': '66%',
  'S Dakota St': '92%',
  'San Diego St': '58%',
  'San Fran': '67%',
  'Seton Hall': '69%',
  "St Mary's": '54%',
  "St Peter's": '99%',
  'TAM C. Christi': '99%',
  'TCU': '64%',
  'Tennessee': '50%',
  'Texas': '65%',
  'Texas Tech': '53%',
  'TX Southern': '99%',
  'UAB': '90%',
  'UCLA': '66%',
  'USC': '85%',
  'Vermont': '84%',
  'Villanova': '50%',
  'Virginia Tech': '80%',
  'Wisconsin': '53%',
  'Wright St': '99%',
  'Wyoming': '82%',
  'Yale': '99%',
  'Akron': '81%',
  'Alabama': '60%'},
 'Arkansas': {'Auburn': '44%',
  'Baylor': '41%',
  'Boise St': '51%',
  'Bryant': '88%',
  'Chatt': '78%',
  'Colgate': '81%',
  'Colo St': '53%',
  'Connecticut': '47%',
  'Creighton': '47%',
  'CS Fullerton': '87%',
  'Davidson': '63%',
  'Delaware': '84%',
  'Duke': '40%',
  'Georgia St': '90%',
  'Gonzaga': '33%',
  'Houston': '43%',
  'Illinois': '47%',
  'Indiana': '80%',
  'Iowa': '54%',
  'Iowa St': '63%',
  'Jville St': '81%',
  'Kansas': '33%',
  'Kentucky': '36%',
  'Longwood': '88%',
  'Loyola-Chi': '71%',
  'LSU': '48%',
  'Marquette': '49%',
  'Memphis': '57%',
  'Miami FL': '79%',
  'Michigan': '56%',
  'Michigan St': '46%',
  'Montana St': '86%',
  'Murray St': '73%',
  'N Mex St': '80%',
  'Norfolk St': '81%',
  'N Carolina': '71%',
  'Notre Dame': '79%',
  'Ohio St': '63%',
  'Providence': '53%',
  'Purdue': '39%',
  'Richmond': '65%',
  'Rutgers': '59%',
  'S Dakota St': '67%',
  'San Diego St': '49%',
  'San Fran': '48%',
  'Seton Hall': '62%',
  "St Mary's": '37%',
  "St Peter's": '84%',
  'TAM C. Christi': '88%',
  'TCU': '53%',
  'Tennessee': '40%',
  'Texas': '50%',
  'Texas Tech': '44%',
  'TX Southern': '81%',
  'UAB': '77%',
  'UCLA': '45%',
  'USC': '72%',
  'Vermont': '72%',
  'Villanova': '38%',
  'Virginia Tech': '69%',
  'Wisconsin': '49%',
  'Wright St': '84%',
  'Wyoming': '80%',
  'Yale': '88%',
  'Akron': '72%',
  'Alabama': '52%',
  'Arizona': '30%'},
 'Auburn': {'Baylor': '42%',
  'Boise St': '54%',
  'Bryant': '99%',
  'Chatt': '85%',
  'Colgate': '85%',
  'Colo St': '59%',
  'Connecticut': '66%',
  'Creighton': '53%',
  'CS Fullerton': '99%',
  'Davidson': '74%',
  'Delaware': '99%',
  'Duke': '56%',
  'Georgia St': '99%',
  'Gonzaga': '46%',
  'Houston': '60%',
  'Illinois': '56%',
  'Indiana': '88%',
  'Iowa': '80%',
  'Iowa St': '76%',
  'Jville St': '99%',
  'Kansas': '43%',
  'Kentucky': '43%',
  'Longwood': '90%',
  'Loyola-Chi': '87%',
  'LSU': '61%',
  'Marquette': '56%',
  'Memphis': '64%',
  'Miami FL': '83%',
  'Michigan': '59%',
  'Michigan St': '54%',
  'Montana St': '94%',
  'Murray St': '85%',
  'N Mex St': '85%',
  'Norfolk St': '99%',
  'N Carolina': '89%',
  'Notre Dame': '82%',
  'Ohio St': '71%',
  'Providence': '59%',
  'Purdue': '48%',
  'Richmond': '75%',
  'Rutgers': '67%',
  'S Dakota St': '80%',
  'San Diego St': '54%',
  'San Fran': '71%',
  'Seton Hall': '81%',
  "St Mary's": '48%',
  "St Peter's": '98%',
  'TAM C. Christi': '99%',
  'TCU': '67%',
  'Tennessee': '44%',
  'Texas': '80%',
  'Texas Tech': '52%',
  'TX Southern': '99%',
  'UAB': '90%',
  'UCLA': '52%',
  'USC': '80%',
  'Vermont': '75%',
  'Villanova': '46%',
  'Virginia Tech': '72%',
  'Wisconsin': '49%',
  'Wright St': '99%',
  'Wyoming': '85%',
  'Yale': '94%',
  'Akron': '73%',
  'Alabama': '54%',
  'Arizona': '45%',
  'Arkansas': '56%'},
 'Baylor': {'Boise St': '61%',
  'Bryant': '99%',
  'Chatt': '82%',
  'Colgate': '99%',
  'Colo St': '63%',
  'Connecticut': '69%',
  'Creighton': '53%',
  'CS Fullerton': '99%',
  'Davidson': '63%',
  'Delaware': '99%',
  'Duke': '58%',
  'Georgia St': '99%',
  'Gonzaga': '51%',
  'Houston': '65%',
  'Illinois': '64%',
  'Indiana': '84%',
  'Iowa': '85%',
  'Iowa St': '66%',
  'Jville St': '99%',
  'Kansas': '47%',
  'Kentucky': '48%',
  'Longwood': '99%',
  'Loyola-Chi': '80%',
  'LSU': '70%',
  'Marquette': '50%',
  'Memphis': '54%',
  'Miami FL': '85%',
  'Michigan': '59%',
  'Michigan St': '47%',
  'Montana St': '99%',
  'Murray St': '81%',
  'N Mex St': '83%',
  'Norfolk St': '99%',
  'N Carolina': '85%',
  'Notre Dame': '87%',
  'Ohio St': '76%',
  'Providence': '67%',
  'Purdue': '50%',
  'Richmond': '70%',
  'Rutgers': '64%',
  'S Dakota St': '79%',
  'San Diego St': '64%',
  'San Fran': '72%',
  'Seton Hall': '77%',
  "St Mary's": '57%',
  "St Peter's": '99%',
  'TAM C. Christi': '99%',
  'TCU': '75%',
  'Tennessee': '50%',
  'Texas': '83%',
  'Texas Tech': '50%',
  'TX Southern': '99%',
  'UAB': '85%',
  'UCLA': '66%',
  'USC': '77%',
  'Vermont': '79%',
  'Villanova': '52%',
  'Virginia Tech': '76%',
  'Wisconsin': '53%',
  'Wright St': '99%',
  'Wyoming': '87%',
  'Yale': '99%',
  'Akron': '78%',
  'Alabama': '56%',
  'Arizona': '49%',
  'Arkansas': '59%',
  'Auburn': '58%'},
 'Boise St': {'Bryant': '85%',
  'Chatt': '79%',
  'Colgate': '86%',
  'Colo St': '60%',
  'Connecticut': '52%',
  'Creighton': '50%',
  'CS Fullerton': '92%',
  'Davidson': '56%',
  'Delaware': '89%',
  'Duke': '50%',
  'Georgia St': '89%',
  'Gonzaga': '35%',
  'Houston': '45%',
  'Illinois': '46%',
  'Indiana': '95%',
  'Iowa': '56%',
  'Iowa St': '81%',
  'Jville St': '86%',
  'Kansas': '38%',
  'Kentucky': '39%',
  'Longwood': '92%',
  'Loyola-Chi': '69%',
  'LSU': '54%',
  'Marquette': '52%',
  'Memphis': '53%',
  'Miami FL': '66%',
  'Michigan': '62%',
  'Michigan St': '47%',
  'Montana St': '89%',
  'Murray St': '60%',
  'N Mex St': '86%',
  'Norfolk St': '89%',
  'N Carolina': '65%',
  'Notre Dame': '99%',
  'Ohio St': '56%',
  'Providence': '59%',
  'Purdue': '45%',
  'Richmond': '73%',
  'Rutgers': '57%',
  'S Dakota St': '68%',
  'San Diego St': '52%',
  'San Fran': '49%',
  'Seton Hall': '60%',
  "St Mary's": '48%',
  "St Peter's": '85%',
  'TAM C. Christi': '92%',
  'TCU': '57%',
  'Tennessee': '40%',
  'Texas': '59%',
  'Texas Tech': '48%',
  'TX Southern': '90%',
  'UAB': '74%',
  'UCLA': '48%',
  'USC': '67%',
  'Vermont': '83%',
  'Villanova': '37%',
  'Virginia Tech': '88%',
  'Wisconsin': '55%',
  'Wright St': '91%',
  'Wyoming': '90%',
  'Yale': '91%',
  'Akron': '79%',
  'Alabama': '49%',
  'Arizona': '42%',
  'Arkansas': '49%',
  'Auburn': '46%',
  'Baylor': '39%'},
 'Bryant': {'Chatt': '32%',
  'Colgate': '43%',
  'Colo St': '25%',
  'Connecticut': '30%',
  'Creighton': '27%',
  'CS Fullerton': '47%',
  'Davidson': '27%',
  'Delaware': '42%',
  'Duke': '3%',
  'Georgia St': '35%',
  'Gonzaga': '2%',
  'Houston': '30%',
  'Illinois': '27%',
  'Indiana': '36%',
  'Iowa': '25%',
  'Iowa St': '30%',
  'Jville St': '38%',
  'Kansas': '6%',
  'Kentucky': '7%',
  'Longwood': '51%',
  'Loyola-Chi': '34%',
  'LSU': '35%',
  'Marquette': '27%',
  'Memphis': '32%',
  'Miami FL': '33%',
  'Michigan': '34%',
  'Michigan St': '30%',
  'Montana St': '41%',
  'Murray St': '28%',
  'N Mex St': '41%',
  'Norfolk St': '50%',
  'N Carolina': '27%',
  'Notre Dame': '32%',
  'Ohio St': '33%',
  'Providence': '28%',
  'Purdue': '14%',
  'Richmond': '32%',
  'Rutgers': '31%',
  'S Dakota St': '37%',
  'San Diego St': '33%',
  'San Fran': '30%',
  'Seton Hall': '32%',
  "St Mary's": '25%',
  "St Peter's": '45%',
  'TAM C. Christi': '50%',
  'TCU': '28%',
  'Tennessee': '12%',
  'Texas': '34%',
  'Texas Tech': '15%',
  'TX Southern': '55%',
  'UAB': '29%',
  'UCLA': '25%',
  'USC': '26%',
  'Vermont': '31%',
  'Villanova': '6%',
  'Virginia Tech': '32%',
  'Wisconsin': '14%',
  'Wright St': '39%',
  'Wyoming': '38%',
  'Yale': '42%',
  'Akron': '45%',
  'Alabama': '21%',
  'Arizona': '1%',
  'Arkansas': '12%',
  'Auburn': '1%',
  'Baylor': '1%',
  'Boise St': '15%'},
 'Chatt': {'Colgate': '54%',
  'Colo St': '33%',
  'Connecticut': '35%',
  'Creighton': '49%',
  'CS Fullerton': '53%',
  'Davidson': '49%',
  'Delaware': '50%',
  'Duke': '29%',
  'Georgia St': '64%',
  'Gonzaga': '25%',
  'Houston': '34%',
  'Illinois': '35%',
  'Indiana': '40%',
  'Iowa': '39%',
  'Iowa St': '36%',
  'Jville St': '54%',
  'Kansas': '28%',
  'Kentucky': '30%',
  'Longwood': '55%',
  'Loyola-Chi': '47%',
  'LSU': '46%',
  'Marquette': '38%',
  'Memphis': '41%',
  'Miami FL': '46%',
  'Michigan': '41%',
  'Michigan St': '40%',
  'Montana St': '49%',
  'Murray St': '50%',
  'N Mex St': '50%',
  'Norfolk St': '69%',
  'N Carolina': '45%',
  'Notre Dame': '50%',
  'Ohio St': '37%',
  'Providence': '39%',
  'Purdue': '34%',
  'Richmond': '49%',
  'Rutgers': '45%',
  'S Dakota St': '53%',
  'San Diego St': '42%',
  'San Fran': '40%',
  'Seton Hall': '38%',
  "St Mary's": '35%',
  "St Peter's": '56%',
  'TAM C. Christi': '70%',
  'TCU': '42%',
  'Tennessee': '32%',
  'Texas': '38%',
  'Texas Tech': '36%',
  'TX Southern': '64%',
  'UAB': '53%',
  'UCLA': '40%',
  'USC': '46%',
  'Vermont': '52%',
  'Villanova': '32%',
  'Virginia Tech': '37%',
  'Wisconsin': '38%',
  'Wright St': '64%',
  'Wyoming': '51%',
  'Yale': '57%',
  'Akron': '69%',
  'Alabama': '29%',
  'Arizona': '18%',
  'Arkansas': '22%',
  'Auburn': '15%',
  'Baylor': '18%',
  'Boise St': '21%',
  'Bryant': '68%'},
 'Colgate': {'Colo St': '29%',
  'Connecticut': '30%',
  'Creighton': '37%',
  'CS Fullerton': '48%',
  'Davidson': '28%',
  'Delaware': '51%',
  'Duke': '26%',
  'Georgia St': '53%',
  'Gonzaga': '6%',
  'Houston': '32%',
  'Illinois': '31%',
  'Indiana': '40%',
  'Iowa': '28%',
  'Iowa St': '34%',
  'Jville St': '50%',
  'Kansas': '11%',
  'Kentucky': '23%',
  'Longwood': '63%',
  'Loyola-Chi': '39%',
  'LSU': '44%',
  'Marquette': '36%',
  'Memphis': '38%',
  'Miami FL': '37%',
  'Michigan': '32%',
  'Michigan St': '31%',
  'Montana St': '49%',
  'Murray St': '31%',
  'N Mex St': '41%',
  'Norfolk St': '53%',
  'N Carolina': '34%',
  'Notre Dame': '37%',
  'Ohio St': '38%',
  'Providence': '30%',
  'Purdue': '26%',
  'Richmond': '34%',
  'Rutgers': '29%',
  'S Dakota St': '37%',
  'San Diego St': '38%',
  'San Fran': '33%',
  'Seton Hall': '38%',
  "St Mary's": '31%',
  "St Peter's": '53%',
  'TAM C. Christi': '53%',
  'TCU': '34%',
  'Tennessee': '26%',
  'Texas': '37%',
  'Texas Tech': '31%',
  'TX Southern': '49%',
  'UAB': '30%',
  'UCLA': '26%',
  'USC': '28%',
  'Vermont': '31%',
  'Villanova': '30%',
  'Virginia Tech': '31%',
  'Wisconsin': '32%',
  'Wright St': '45%',
  'Wyoming': '38%',
  'Yale': '59%',
  'Akron': '51%',
  'Alabama': '25%',
  'Arizona': '1%',
  'Arkansas': '19%',
  'Auburn': '15%',
  'Baylor': '1%',
  'Boise St': '14%',
  'Bryant': '57%',
  'Chatt': '46%'},
 'Colo St': {'Connecticut': '48%',
  'Creighton': '59%',
  'CS Fullerton': '89%',
  'Davidson': '62%',
  'Delaware': '87%',
  'Duke': '40%',
  'Georgia St': '84%',
  'Gonzaga': '30%',
  'Houston': '39%',
  'Illinois': '46%',
  'Indiana': '84%',
  'Iowa': '49%',
  'Iowa St': '74%',
  'Jville St': '87%',
  'Kansas': '32%',
  'Kentucky': '36%',
  'Longwood': '92%',
  'Loyola-Chi': '73%',
  'LSU': '48%',
  'Marquette': '63%',
  'Memphis': '58%',
  'Miami FL': '89%',
  'Michigan': '60%',
  'Michigan St': '52%',
  'Montana St': '85%',
  'Murray St': '53%',
  'N Mex St': '77%',
  'Norfolk St': '84%',
  'N Carolina': '63%',
  'Notre Dame': '99%',
  'Ohio St': '49%',
  'Providence': '58%',
  'Purdue': '40%',
  'Richmond': '63%',
  'Rutgers': '67%',
  'S Dakota St': '67%',
  'San Diego St': '44%',
  'San Fran': '48%',
  'Seton Hall': '57%',
  "St Mary's": '42%',
  "St Peter's": '80%',
  'TAM C. Christi': '89%',
  'TCU': '72%',
  'Tennessee': '38%',
  'Texas': '55%',
  'Texas Tech': '44%',
  'TX Southern': '79%',
  'UAB': '71%',
  'UCLA': '47%',
  'USC': '64%',
  'Vermont': '71%',
  'Villanova': '40%',
  'Virginia Tech': '76%',
  'Wisconsin': '44%',
  'Wright St': '90%',
  'Wyoming': '85%',
  'Yale': '89%',
  'Akron': '74%',
  'Alabama': '51%',
  'Arizona': '42%',
  'Arkansas': '47%',
  'Auburn': '41%',
  'Baylor': '37%',
  'Boise St': '40%',
  'Bryant': '75%',
  'Chatt': '67%',
  'Colgate': '71%'},
 'Connecticut': {'Creighton': '39%',
  'CS Fullerton': '88%',
  'Davidson': '57%',
  'Delaware': '84%',
  'Duke': '47%',
  'Georgia St': '89%',
  'Gonzaga': '38%',
  'Houston': '48%',
  'Illinois': '48%',
  'Indiana': '80%',
  'Iowa': '53%',
  'Iowa St': '62%',
  'Jville St': '83%',
  'Kansas': '36%',
  'Kentucky': '37%',
  'Longwood': '84%',
  'Loyola-Chi': '74%',
  'LSU': '50%',
  'Marquette': '49%',
  'Memphis': '57%',
  'Miami FL': '73%',
  'Michigan': '57%',
  'Michigan St': '40%',
  'Montana St': '83%',
  'Murray St': '57%',
  'N Mex St': '86%',
  'Norfolk St': '86%',
  'N Carolina': '76%',
  'Notre Dame': '79%',
  'Ohio St': '56%',
  'Providence': '58%',
  'Purdue': '38%',
  'Richmond': '64%',
  'Rutgers': '54%',
  'S Dakota St': '62%',
  'San Diego St': '55%',
  'San Fran': '66%',
  'Seton Hall': '74%',
  "St Mary's": '44%',
  "St Peter's": '83%',
  'TAM C. Christi': '91%',
  'TCU': '55%',
  'Tennessee': '37%',
  'Texas': '61%',
  'Texas Tech': '51%',
  'TX Southern': '87%',
  'UAB': '70%',
  'UCLA': '51%',
  'USC': '55%',
  'Vermont': '67%',
  'Villanova': '37%',
  'Virginia Tech': '64%',
  'Wisconsin': '53%',
  'Wright St': '86%',
  'Wyoming': '75%',
  'Yale': '86%',
  'Akron': '73%',
  'Alabama': '55%',
  'Arizona': '36%',
  'Arkansas': '53%',
  'Auburn': '34%',
  'Baylor': '31%',
  'Boise St': '48%',
  'Bryant': '70%',
  'Chatt': '65%',
  'Colgate': '70%',
  'Colo St': '52%'},
 'Creighton': {'CS Fullerton': '82%',
  'Davidson': '53%',
  'Delaware': '83%',
  'Duke': '45%',
  'Georgia St': '81%',
  'Gonzaga': '31%',
  'Houston': '51%',
  'Illinois': '46%',
  'Indiana': '77%',
  'Iowa': '48%',
  'Iowa St': '53%',
  'Jville St': '83%',
  'Kansas': '31%',
  'Kentucky': '33%',
  'Longwood': '80%',
  'Loyola-Chi': '60%',
  'LSU': '49%',
  'Marquette': '49%',
  'Memphis': '52%',
  'Miami FL': '56%',
  'Michigan': '45%',
  'Michigan St': '49%',
  'Montana St': '73%',
  'Murray St': '49%',
  'N Mex St': '80%',
  'Norfolk St': '82%',
  'N Carolina': '61%',
  'Notre Dame': '63%',
  'Ohio St': '54%',
  'Providence': '53%',
  'Purdue': '39%',
  'Richmond': '61%',
  'Rutgers': '58%',
  'S Dakota St': '58%',
  'San Diego St': '50%',
  'San Fran': '56%',
  'Seton Hall': '54%',
  "St Mary's": '44%',
  "St Peter's": '81%',
  'TAM C. Christi': '83%',
  'TCU': '55%',
  'Tennessee': '32%',
  'Texas': '54%',
  'Texas Tech': '44%',
  'TX Southern': '85%',
  'UAB': '57%',
  'UCLA': '44%',
  'USC': '47%',
  'Vermont': '57%',
  'Villanova': '29%',
  'Virginia Tech': '52%',
  'Wisconsin': '47%',
  'Wright St': '89%',
  'Wyoming': '78%',
  'Yale': '88%',
  'Akron': '69%',
  'Alabama': '40%',
  'Arizona': '40%',
  'Arkansas': '53%',
  'Auburn': '47%',
  'Baylor': '47%',
  'Boise St': '50%',
  'Bryant': '73%',
  'Chatt': '51%',
  'Colgate': '63%',
  'Colo St': '41%',
  'Connecticut': '61%'},
 'CS Fullerton': {'Davidson': '26%',
  'Delaware': '40%',
  'Duke': '11%',
  'Georgia St': '42%',
  'Gonzaga': '2%',
  'Houston': '27%',
  'Illinois': '23%',
  'Indiana': '30%',
  'Iowa': '25%',
  'Iowa St': '28%',
  'Jville St': '47%',
  'Kansas': '3%',
  'Kentucky': '7%',
  'Longwood': '47%',
  'Loyola-Chi': '29%',
  'LSU': '33%',
  'Marquette': '28%',
  'Memphis': '32%',
  'Miami FL': '26%',
  'Michigan': '29%',
  'Michigan St': '24%',
  'Montana St': '50%',
  'Murray St': '28%',
  'N Mex St': '32%',
  'Norfolk St': '46%',
  'N Carolina': '28%',
  'Notre Dame': '30%',
  'Ohio St': '31%',
  'Providence': '25%',
  'Purdue': '23%',
  'Richmond': '28%',
  'Rutgers': '25%',
  'S Dakota St': '34%',
  'San Diego St': '23%',
  'San Fran': '23%',
  'Seton Hall': '30%',
  "St Mary's": '20%',
  "St Peter's": '42%',
  'TAM C. Christi': '49%',
  'TCU': '29%',
  'Tennessee': '20%',
  'Texas': '30%',
  'Texas Tech': '23%',
  'TX Southern': '50%',
  'UAB': '26%',
  'UCLA': '19%',
  'USC': '26%',
  'Vermont': '41%',
  'Villanova': '8%',
  'Virginia Tech': '29%',
  'Wisconsin': '22%',
  'Wright St': '49%',
  'Wyoming': '28%',
  'Yale': '42%',
  'Akron': '49%',
  'Alabama': '18%',
  'Arizona': '1%',
  'Arkansas': '13%',
  'Auburn': '1%',
  'Baylor': '1%',
  'Boise St': '8%',
  'Bryant': '53%',
  'Chatt': '47%',
  'Colgate': '52%',
  'Colo St': '11%',
  'Connecticut': '12%',
  'Creighton': '18%'},
 'Davidson': {'Delaware': '84%',
  'Duke': '33%',
  'Georgia St': '81%',
  'Gonzaga': '26%',
  'Houston': '37%',
  'Illinois': '41%',
  'Indiana': '51%',
  'Iowa': '42%',
  'Iowa St': '45%',
  'Jville St': '84%',
  'Kansas': '39%',
  'Kentucky': '35%',
  'Longwood': '85%',
  'Loyola-Chi': '56%',
  'LSU': '44%',
  'Marquette': '47%',
  'Memphis': '49%',
  'Miami FL': '53%',
  'Michigan': '44%',
  'Michigan St': '49%',
  'Montana St': '82%',
  'Murray St': '59%',
  'N Mex St': '58%',
  'Norfolk St': '86%',
  'N Carolina': '52%',
  'Notre Dame': '60%',
  'Ohio St': '45%',
  'Providence': '45%',
  'Purdue': '38%',
  'Richmond': '45%',
  'Rutgers': '45%',
  'S Dakota St': '67%',
  'San Diego St': '45%',
  'San Fran': '44%',
  'Seton Hall': '47%',
  "St Mary's": '36%',
  "St Peter's": '72%',
  'TAM C. Christi': '87%',
  'TCU': '46%',
  'Tennessee': '38%',
  'Texas': '38%',
  'Texas Tech': '40%',
  'TX Southern': '82%',
  'UAB': '63%',
  'UCLA': '39%',
  'USC': '49%',
  'Vermont': '72%',
  'Villanova': '32%',
  'Virginia Tech': '40%',
  'Wisconsin': '40%',
  'Wright St': '85%',
  'Wyoming': '57%',
  'Yale': '83%',
  'Akron': '77%',
  'Alabama': '44%',
  'Arizona': '27%',
  'Arkansas': '37%',
  'Auburn': '26%',
  'Baylor': '37%',
  'Boise St': '44%',
  'Bryant': '73%',
  'Chatt': '51%',
  'Colgate': '72%',
  'Colo St': '38%',
  'Connecticut': '43%',
  'Creighton': '47%',
  'CS Fullerton': '74%'},
 'Delaware': {'Duke': '10%',
  'Georgia St': '54%',
  'Gonzaga': '2%',
  'Houston': '27%',
  'Illinois': '26%',
  'Indiana': '34%',
  'Iowa': '25%',
  'Iowa St': '29%',
  'Jville St': '52%',
  'Kansas': '3%',
  'Kentucky': '8%',
  'Longwood': '52%',
  'Loyola-Chi': '37%',
  'LSU': '36%',
  'Marquette': '31%',
  'Memphis': '35%',
  'Miami FL': '30%',
  'Michigan': '32%',
  'Michigan St': '28%',
  'Montana St': '52%',
  'Murray St': '39%',
  'N Mex St': '39%',
  'Norfolk St': '58%',
  'N Carolina': '27%',
  'Notre Dame': '32%',
  'Ohio St': '32%',
  'Providence': '25%',
  'Purdue': '22%',
  'Richmond': '32%',
  'Rutgers': '27%',
  'S Dakota St': '45%',
  'San Diego St': '31%',
  'San Fran': '27%',
  'Seton Hall': '34%',
  "St Mary's": '23%',
  "St Peter's": '52%',
  'TAM C. Christi': '56%',
  'TCU': '30%',
  'Tennessee': '21%',
  'Texas': '32%',
  'Texas Tech': '27%',
  'TX Southern': '50%',
  'UAB': '33%',
  'UCLA': '21%',
  'USC': '28%',
  'Vermont': '42%',
  'Villanova': '10%',
  'Virginia Tech': '30%',
  'Wisconsin': '24%',
  'Wright St': '48%',
  'Wyoming': '33%',
  'Yale': '53%',
  'Akron': '56%',
  'Alabama': '23%',
  'Arizona': '1%',
  'Arkansas': '16%',
  'Auburn': '1%',
  'Baylor': '1%',
  'Boise St': '11%',
  'Bryant': '58%',
  'Chatt': '50%',
  'Colgate': '49%',
  'Colo St': '13%',
  'Connecticut': '16%',
  'Creighton': '17%',
  'CS Fullerton': '60%',
  'Davidson': '16%'},
 'Duke': {'Georgia St': '99%',
  'Gonzaga': '41%',
  'Houston': '57%',
  'Illinois': '50%',
  'Indiana': '66%',
  'Iowa': '70%',
  'Iowa St': '59%',
  'Jville St': '99%',
  'Kansas': '47%',
  'Kentucky': '47%',
  'Longwood': '87%',
  'Loyola-Chi': '79%',
  'LSU': '59%',
  'Marquette': '51%',
  'Memphis': '59%',
  'Miami FL': '60%',
  'Michigan': '55%',
  'Michigan St': '49%',
  'Montana St': '88%',
  'Murray St': '67%',
  'N Mex St': '74%',
  'Norfolk St': '99%',
  'N Carolina': '63%',
  'Notre Dame': '75%',
  'Ohio St': '65%',
  'Providence': '56%',
  'Purdue': '48%',
  'Richmond': '55%',
  'Rutgers': '55%',
  'S Dakota St': '83%',
  'San Diego St': '56%',
  'San Fran': '60%',
  'Seton Hall': '66%',
  "St Mary's": '56%',
  "St Peter's": '92%',
  'TAM C. Christi': '99%',
  'TCU': '53%',
  'Tennessee': '48%',
  'Texas': '67%',
  'Texas Tech': '51%',
  'TX Southern': '99%',
  'UAB': '67%',
  'UCLA': '53%',
  'USC': '65%',
  'Vermont': '75%',
  'Villanova': '48%',
  'Virginia Tech': '63%',
  'Wisconsin': '50%',
  'Wright St': '99%',
  'Wyoming': '62%',
  'Yale': '91%',
  'Akron': '75%',
  'Alabama': '49%',
  'Arizona': '41%',
  'Arkansas': '60%',
  'Auburn': '44%',
  'Baylor': '42%',
  'Boise St': '50%',
  'Bryant': '97%',
  'Chatt': '71%',
  'Colgate': '74%',
  'Colo St': '60%',
  'Connecticut': '53%',
  'Creighton': '55%',
  'CS Fullerton': '89%',
  'Davidson': '67%',
  'Delaware': '90%'},
 'Georgia St': {'Gonzaga': '2%',
  'Houston': '30%',
  'Illinois': '25%',
  'Indiana': '34%',
  'Iowa': '26%',
  'Iowa St': '26%',
  'Jville St': '43%',
  'Kansas': '4%',
  'Kentucky': '4%',
  'Longwood': '48%',
  'Loyola-Chi': '30%',
  'LSU': '31%',
  'Marquette': '26%',
  'Memphis': '31%',
  'Miami FL': '25%',
  'Michigan': '34%',
  'Michigan St': '27%',
  'Montana St': '50%',
  'Murray St': '32%',
  'N Mex St': '32%',
  'Norfolk St': '50%',
  'N Carolina': '29%',
  'Notre Dame': '26%',
  'Ohio St': '28%',
  'Providence': '28%',
  'Purdue': '17%',
  'Richmond': '23%',
  'Rutgers': '25%',
  'S Dakota St': '40%',
  'San Diego St': '23%',
  'San Fran': '24%',
  'Seton Hall': '29%',
  "St Mary's": '24%',
  "St Peter's": '41%',
  'TAM C. Christi': '53%',
  'TCU': '26%',
  'Tennessee': '8%',
  'Texas': '29%',
  'Texas Tech': '16%',
  'TX Southern': '50%',
  'UAB': '27%',
  'UCLA': '21%',
  'USC': '29%',
  'Vermont': '43%',
  'Villanova': '6%',
  'Virginia Tech': '26%',
  'Wisconsin': '14%',
  'Wright St': '44%',
  'Wyoming': '30%',
  'Yale': '38%',
  'Akron': '45%',
  'Alabama': '20%',
  'Arizona': '1%',
  'Arkansas': '10%',
  'Auburn': '1%',
  'Baylor': '1%',
  'Boise St': '11%',
  'Bryant': '65%',
  'Chatt': '36%',
  'Colgate': '47%',
  'Colo St': '16%',
  'Connecticut': '11%',
  'Creighton': '19%',
  'CS Fullerton': '58%',
  'Davidson': '19%',
  'Delaware': '46%',
  'Duke': '1%'},
 'Gonzaga': {'Houston': '54%',
  'Illinois': '75%',
  'Indiana': '91%',
  'Iowa': '83%',
  'Iowa St': '85%',
  'Jville St': '99%',
  'Kansas': '59%',
  'Kentucky': '58%',
  'Longwood': '99%',
  'Loyola-Chi': '84%',
  'LSU': '69%',
  'Marquette': '74%',
  'Memphis': '81%',
  'Miami FL': '83%',
  'Michigan': '78%',
  'Michigan St': '73%',
  'Montana St': '99%',
  'Murray St': '81%',
  'N Mex St': '85%',
  'Norfolk St': '99%',
  'N Carolina': '87%',
  'Notre Dame': '92%',
  'Ohio St': '83%',
  'Providence': '73%',
  'Purdue': '58%',
  'Richmond': '81%',
  'Rutgers': '84%',
  'S Dakota St': '82%',
  'San Diego St': '69%',
  'San Fran': '74%',
  'Seton Hall': '81%',
  "St Mary's": '62%',
  "St Peter's": '99%',
  'TAM C. Christi': '99%',
  'TCU': '81%',
  'Tennessee': '56%',
  'Texas': '71%',
  'Texas Tech': '56%',
  'TX Southern': '99%',
  'UAB': '86%',
  'UCLA': '67%',
  'USC': '85%',
  'Vermont': '77%',
  'Villanova': '61%',
  'Virginia Tech': '78%',
  'Wisconsin': '63%',
  'Wright St': '99%',
  'Wyoming': '90%',
  'Yale': '99%',
  'Akron': '84%',
  'Alabama': '64%',
  'Arizona': '49%',
  'Arkansas': '67%',
  'Auburn': '54%',
  'Baylor': '49%',
  'Boise St': '65%',
  'Bryant': '98%',
  'Chatt': '75%',
  'Colgate': '94%',
  'Colo St': '70%',
  'Connecticut': '62%',
  'Creighton': '69%',
  'CS Fullerton': '98%',
  'Davidson': '74%',
  'Delaware': '98%',
  'Duke': '59%',
  'Georgia St': '98%'},
 'Houston': {'Illinois': '54%',
  'Indiana': '72%',
  'Iowa': '61%',
  'Iowa St': '59%',
  'Jville St': '67%',
  'Kansas': '49%',
  'Kentucky': '45%',
  'Longwood': '75%',
  'Loyola-Chi': '68%',
  'LSU': '54%',
  'Marquette': '50%',
  'Memphis': '59%',
  'Miami FL': '53%',
  'Michigan': '50%',
  'Michigan St': '48%',
  'Montana St': '71%',
  'Murray St': '52%',
  'N Mex St': '67%',
  'Norfolk St': '76%',
  'N Carolina': '67%',
  'Notre Dame': '61%',
  'Ohio St': '53%',
  'Providence': '53%',
  'Purdue': '50%',
  'Richmond': '51%',
  'Rutgers': '58%',
  'S Dakota St': '62%',
  'San Diego St': '56%',
  'San Fran': '57%',
  'Seton Hall': '70%',
  "St Mary's": '47%',
  "St Peter's": '71%',
  'TAM C. Christi': '80%',
  'TCU': '53%',
  'Tennessee': '50%',
  'Texas': '59%',
  'Texas Tech': '54%',
  'TX Southern': '76%',
  'UAB': '60%',
  'UCLA': '52%',
  'USC': '54%',
  'Vermont': '62%',
  'Villanova': '50%',
  'Virginia Tech': '60%',
  'Wisconsin': '52%',
  'Wright St': '76%',
  'Wyoming': '65%',
  'Yale': '72%',
  'Akron': '73%',
  'Alabama': '49%',
  'Arizona': '38%',
  'Arkansas': '57%',
  'Auburn': '40%',
  'Baylor': '35%',
  'Boise St': '55%',
  'Bryant': '70%',
  'Chatt': '66%',
  'Colgate': '68%',
  'Colo St': '61%',
  'Connecticut': '52%',
  'Creighton': '49%',
  'CS Fullerton': '73%',
  'Davidson': '63%',
  'Delaware': '73%',
  'Duke': '43%',
  'Georgia St': '70%',
  'Gonzaga': '46%'},
 'Illinois': {'Indiana': '74%',
  'Iowa': '50%',
  'Iowa St': '66%',
  'Jville St': '78%',
  'Kansas': '38%',
  'Kentucky': '37%',
  'Longwood': '81%',
  'Loyola-Chi': '70%',
  'LSU': '49%',
  'Marquette': '48%',
  'Memphis': '51%',
  'Miami FL': '74%',
  'Michigan': '67%',
  'Michigan St': '39%',
  'Montana St': '80%',
  'Murray St': '64%',
  'N Mex St': '79%',
  'Norfolk St': '78%',
  'N Carolina': '79%',
  'Notre Dame': '80%',
  'Ohio St': '76%',
  'Providence': '55%',
  'Purdue': '40%',
  'Richmond': '69%',
  'Rutgers': '51%',
  'S Dakota St': '61%',
  'San Diego St': '57%',
  'San Fran': '65%',
  'Seton Hall': '73%',
  "St Mary's": '45%',
  "St Peter's": '78%',
  'TAM C. Christi': '82%',
  'TCU': '73%',
  'Tennessee': '38%',
  'Texas': '60%',
  'Texas Tech': '43%',
  'TX Southern': '78%',
  'UAB': '62%',
  'UCLA': '40%',
  'USC': '66%',
  'Vermont': '64%',
  'Villanova': '33%',
  'Virginia Tech': '65%',
  'Wisconsin': '53%',
  'Wright St': '90%',
  'Wyoming': '85%',
  'Yale': '87%',
  'Akron': '75%',
  'Alabama': '57%',
  'Arizona': '38%',
  'Arkansas': '53%',
  'Auburn': '44%',
  'Baylor': '36%',
  'Boise St': '54%',
  'Bryant': '73%',
  'Chatt': '65%',
  'Colgate': '69%',
  'Colo St': '54%',
  'Connecticut': '52%',
  'Creighton': '54%',
  'CS Fullerton': '77%',
  'Davidson': '59%',
  'Delaware': '74%',
  'Duke': '50%',
  'Georgia St': '75%',
  'Gonzaga': '25%',
  'Houston': '46%'},
 'Indiana': {'Iowa': '34%',
  'Iowa St': '43%',
  'Jville St': '73%',
  'Kansas': '23%',
  'Kentucky': '21%',
  'Longwood': '62%',
  'Loyola-Chi': '49%',
  'LSU': '42%',
  'Marquette': '42%',
  'Memphis': '43%',
  'Miami FL': '54%',
  'Michigan': '45%',
  'Michigan St': '40%',
  'Montana St': '58%',
  'Murray St': '46%',
  'N Mex St': '57%',
  'Norfolk St': '76%',
  'N Carolina': '38%',
  'Notre Dame': '58%',
  'Ohio St': '43%',
  'Providence': '40%',
  'Purdue': '26%',
  'Richmond': '42%',
  'Rutgers': '48%',
  'S Dakota St': '55%',
  'San Diego St': '32%',
  'San Fran': '33%',
  'Seton Hall': '51%',
  "St Mary's": '28%',
  "St Peter's": '73%',
  'TAM C. Christi': '84%',
  'TCU': '47%',
  'Tennessee': '22%',
  'Texas': '45%',
  'Texas Tech': '32%',
  'TX Southern': '81%',
  'UAB': '50%',
  'UCLA': '28%',
  'USC': '47%',
  'Vermont': '54%',
  'Villanova': '24%',
  'Virginia Tech': '46%',
  'Wisconsin': '32%',
  'Wright St': '77%',
  'Wyoming': '57%',
  'Yale': '66%',
  'Akron': '66%',
  'Alabama': '30%',
  'Arizona': '23%',
  'Arkansas': '20%',
  'Auburn': '12%',
  'Baylor': '16%',
  'Boise St': '5%',
  'Bryant': '64%',
  'Chatt': '60%',
  'Colgate': '60%',
  'Colo St': '16%',
  'Connecticut': '20%',
  'Creighton': '23%',
  'CS Fullerton': '70%',
  'Davidson': '49%',
  'Delaware': '66%',
  'Duke': '34%',
  'Georgia St': '66%',
  'Gonzaga': '9%',
  'Houston': '28%',
  'Illinois': '26%'},
 'Iowa': {'Iowa St': '48%',
  'Jville St': '81%',
  'Kansas': '38%',
  'Kentucky': '44%',
  'Longwood': '82%',
  'Loyola-Chi': '69%',
  'LSU': '46%',
  'Marquette': '42%',
  'Memphis': '54%',
  'Miami FL': '53%',
  'Michigan': '59%',
  'Michigan St': '45%',
  'Montana St': '79%',
  'Murray St': '57%',
  'N Mex St': '80%',
  'Norfolk St': '80%',
  'N Carolina': '58%',
  'Notre Dame': '61%',
  'Ohio St': '51%',
  'Providence': '53%',
  'Purdue': '47%',
  'Richmond': '70%',
  'Rutgers': '54%',
  'S Dakota St': '70%',
  'San Diego St': '56%',
  'San Fran': '56%',
  'Seton Hall': '57%',
  "St Mary's": '50%',
  "St Peter's": '73%',
  'TAM C. Christi': '87%',
  'TCU': '46%',
  'Tennessee': '39%',
  'Texas': '50%',
  'Texas Tech': '45%',
  'TX Southern': '76%',
  'UAB': '60%',
  'UCLA': '43%',
  'USC': '53%',
  'Vermont': '69%',
  'Villanova': '45%',
  'Virginia Tech': '58%',
  'Wisconsin': '50%',
  'Wright St': '81%',
  'Wyoming': '65%',
  'Yale': '86%',
  'Akron': '74%',
  'Alabama': '53%',
  'Arizona': '17%',
  'Arkansas': '46%',
  'Auburn': '20%',
  'Baylor': '15%',
  'Boise St': '44%',
  'Bryant': '75%',
  'Chatt': '61%',
  'Colgate': '72%',
  'Colo St': '51%',
  'Connecticut': '47%',
  'Creighton': '52%',
  'CS Fullerton': '75%',
  'Davidson': '58%',
  'Delaware': '75%',
  'Duke': '30%',
  'Georgia St': '74%',
  'Gonzaga': '17%',
  'Houston': '39%',
  'Illinois': '50%',
  'Indiana': '66%'},
 'Iowa St': {'Jville St': '81%',
  'Kansas': '26%',
  'Kentucky': '25%',
  'Longwood': '81%',
  'Loyola-Chi': '51%',
  'LSU': '37%',
  'Marquette': '46%',
  'Memphis': '45%',
  'Miami FL': '53%',
  'Michigan': '43%',
  'Michigan St': '41%',
  'Montana St': '75%',
  'Murray St': '47%',
  'N Mex St': '62%',
  'Norfolk St': '87%',
  'N Carolina': '42%',
  'Notre Dame': '64%',
  'Ohio St': '48%',
  'Providence': '42%',
  'Purdue': '32%',
  'Richmond': '49%',
  'Rutgers': '54%',
  'S Dakota St': '53%',
  'San Diego St': '34%',
  'San Fran': '36%',
  'Seton Hall': '56%',
  "St Mary's": '26%',
  "St Peter's": '85%',
  'TAM C. Christi': '86%',
  'TCU': '48%',
  'Tennessee': '22%',
  'Texas': '53%',
  'Texas Tech': '31%',
  'TX Southern': '86%',
  'UAB': '49%',
  'UCLA': '33%',
  'USC': '47%',
  'Vermont': '55%',
  'Villanova': '24%',
  'Virginia Tech': '37%',
  'Wisconsin': '34%',
  'Wright St': '81%',
  'Wyoming': '57%',
  'Yale': '91%',
  'Akron': '68%',
  'Alabama': '40%',
  'Arizona': '33%',
  'Arkansas': '37%',
  'Auburn': '24%',
  'Baylor': '34%',
  'Boise St': '19%',
  'Bryant': '70%',
  'Chatt': '64%',
  'Colgate': '66%',
  'Colo St': '26%',
  'Connecticut': '38%',
  'Creighton': '47%',
  'CS Fullerton': '72%',
  'Davidson': '55%',
  'Delaware': '71%',
  'Duke': '41%',
  'Georgia St': '74%',
  'Gonzaga': '15%',
  'Houston': '41%',
  'Illinois': '34%',
  'Indiana': '57%',
  'Iowa': '52%'},
 'Jville St': {'Kansas': '4%',
  'Kentucky': '9%',
  'Longwood': '55%',
  'Loyola-Chi': '29%',
  'LSU': '36%',
  'Marquette': '33%',
  'Memphis': '34%',
  'Miami FL': '29%',
  'Michigan': '30%',
  'Michigan St': '26%',
  'Montana St': '45%',
  'Murray St': '30%',
  'N Mex St': '30%',
  'Norfolk St': '58%',
  'N Carolina': '28%',
  'Notre Dame': '32%',
  'Ohio St': '33%',
  'Providence': '25%',
  'Purdue': '22%',
  'Richmond': '28%',
  'Rutgers': '26%',
  'S Dakota St': '37%',
  'San Diego St': '28%',
  'San Fran': '26%',
  'Seton Hall': '34%',
  "St Mary's": '21%',
  "St Peter's": '49%',
  'TAM C. Christi': '53%',
  'TCU': '30%',
  'Tennessee': '23%',
  'Texas': '34%',
  'Texas Tech': '26%',
  'TX Southern': '50%',
  'UAB': '26%',
  'UCLA': '22%',
  'USC': '26%',
  'Vermont': '33%',
  'Villanova': '10%',
  'Virginia Tech': '27%',
  'Wisconsin': '23%',
  'Wright St': '39%',
  'Wyoming': '32%',
  'Yale': '52%',
  'Akron': '48%',
  'Alabama': '25%',
  'Arizona': '1%',
  'Arkansas': '19%',
  'Auburn': '1%',
  'Baylor': '1%',
  'Boise St': '14%',
  'Bryant': '62%',
  'Chatt': '46%',
  'Colgate': '50%',
  'Colo St': '13%',
  'Connecticut': '17%',
  'Creighton': '17%',
  'CS Fullerton': '53%',
  'Davidson': '16%',
  'Delaware': '48%',
  'Duke': '1%',
  'Georgia St': '57%',
  'Gonzaga': '1%',
  'Houston': '33%',
  'Illinois': '22%',
  'Indiana': '27%',
  'Iowa': '19%',
  'Iowa St': '19%'},
 'Kansas': {'Kentucky': '51%',
  'Longwood': '99%',
  'Loyola-Chi': '85%',
  'LSU': '77%',
  'Marquette': '74%',
  'Memphis': '73%',
  'Miami FL': '87%',
  'Michigan': '73%',
  'Michigan St': '55%',
  'Montana St': '99%',
  'Murray St': '83%',
  'N Mex St': '86%',
  'Norfolk St': '99%',
  'N Carolina': '92%',
  'Notre Dame': '88%',
  'Ohio St': '78%',
  'Providence': '76%',
  'Purdue': '55%',
  'Richmond': '84%',
  'Rutgers': '68%',
  'S Dakota St': '84%',
  'San Diego St': '81%',
  'San Fran': '89%',
  'Seton Hall': '78%',
  "St Mary's": '59%',
  "St Peter's": '99%',
  'TAM C. Christi': '99%',
  'TCU': '82%',
  'Tennessee': '51%',
  'Texas': '82%',
  'Texas Tech': '60%',
  'TX Southern': '99%',
  'UAB': '84%',
  'UCLA': '79%',
  'USC': '85%',
  'Vermont': '73%',
  'Villanova': '48%',
  'Virginia Tech': '80%',
  'Wisconsin': '57%',
  'Wright St': '99%',
  'Wyoming': '90%',
  'Yale': '99%',
  'Akron': '78%',
  'Alabama': '60%',
  'Arizona': '42%',
  'Arkansas': '67%',
  'Auburn': '57%',
  'Baylor': '53%',
  'Boise St': '62%',
  'Bryant': '94%',
  'Chatt': '72%',
  'Colgate': '89%',
  'Colo St': '68%',
  'Connecticut': '64%',
  'Creighton': '69%',
  'CS Fullerton': '97%',
  'Davidson': '61%',
  'Delaware': '97%',
  'Duke': '53%',
  'Georgia St': '96%',
  'Gonzaga': '41%',
  'Houston': '51%',
  'Illinois': '62%',
  'Indiana': '77%',
  'Iowa': '62%',
  'Iowa St': '74%',
  'Jville St': '96%'},
 'Kentucky': {'Longwood': '92%',
  'Loyola-Chi': '79%',
  'LSU': '72%',
  'Marquette': '69%',
  'Memphis': '74%',
  'Miami FL': '86%',
  'Michigan': '70%',
  'Michigan St': '59%',
  'Montana St': '87%',
  'Murray St': '75%',
  'N Mex St': '81%',
  'Norfolk St': '99%',
  'N Carolina': '92%',
  'Notre Dame': '91%',
  'Ohio St': '76%',
  'Providence': '58%',
  'Purdue': '55%',
  'Richmond': '71%',
  'Rutgers': '65%',
  'S Dakota St': '83%',
  'San Diego St': '66%',
  'San Fran': '73%',
  'Seton Hall': '73%',
  "St Mary's": '69%',
  "St Peter's": '99%',
  'TAM C. Christi': '99%',
  'TCU': '79%',
  'Tennessee': '51%',
  'Texas': '86%',
  'Texas Tech': '55%',
  'TX Southern': '99%',
  'UAB': '81%',
  'UCLA': '59%',
  'USC': '80%',
  'Vermont': '75%',
  'Villanova': '56%',
  'Virginia Tech': '79%',
  'Wisconsin': '53%',
  'Wright St': '99%',
  'Wyoming': '91%',
  'Yale': '93%',
  'Akron': '79%',
  'Alabama': '56%',
  'Arizona': '50%',
  'Arkansas': '64%',
  'Auburn': '57%',
  'Baylor': '52%',
  'Boise St': '61%',
  'Bryant': '93%',
  'Chatt': '70%',
  'Colgate': '77%',
  'Colo St': '64%',
  'Connecticut': '63%',
  'Creighton': '67%',
  'CS Fullerton': '93%',
  'Davidson': '65%',
  'Delaware': '92%',
  'Duke': '53%',
  'Georgia St': '96%',
  'Gonzaga': '42%',
  'Houston': '55%',
  'Illinois': '63%',
  'Indiana': '79%',
  'Iowa': '56%',
  'Iowa St': '75%',
  'Jville St': '91%',
  'Kansas': '49%'},
 'Longwood': {'Loyola-Chi': '33%',
  'LSU': '40%',
  'Marquette': '32%',
  'Memphis': '35%',
  'Miami FL': '33%',
  'Michigan': '33%',
  'Michigan St': '32%',
  'Montana St': '41%',
  'Murray St': '25%',
  'N Mex St': '37%',
  'Norfolk St': '50%',
  'N Carolina': '31%',
  'Notre Dame': '30%',
  'Ohio St': '35%',
  'Providence': '31%',
  'Purdue': '25%',
  'Richmond': '37%',
  'Rutgers': '30%',
  'S Dakota St': '34%',
  'San Diego St': '30%',
  'San Fran': '28%',
  'Seton Hall': '35%',
  "St Mary's": '26%',
  "St Peter's": '50%',
  'TAM C. Christi': '51%',
  'TCU': '32%',
  'Tennessee': '21%',
  'Texas': '33%',
  'Texas Tech': '25%',
  'TX Southern': '45%',
  'UAB': '26%',
  'UCLA': '21%',
  'USC': '28%',
  'Vermont': '35%',
  'Villanova': '23%',
  'Virginia Tech': '30%',
  'Wisconsin': '27%',
  'Wright St': '40%',
  'Wyoming': '34%',
  'Yale': '50%',
  'Akron': '49%',
  'Alabama': '26%',
  'Arizona': '1%',
  'Arkansas': '12%',
  'Auburn': '10%',
  'Baylor': '1%',
  'Boise St': '8%',
  'Bryant': '49%',
  'Chatt': '45%',
  'Colgate': '37%',
  'Colo St': '8%',
  'Connecticut': '16%',
  'Creighton': '20%',
  'CS Fullerton': '53%',
  'Davidson': '15%',
  'Delaware': '48%',
  'Duke': '13%',
  'Georgia St': '52%',
  'Gonzaga': '1%',
  'Houston': '25%',
  'Illinois': '19%',
  'Indiana': '38%',
  'Iowa': '18%',
  'Iowa St': '19%',
  'Jville St': '45%',
  'Kansas': '1%',
  'Kentucky': '8%'},
 'Loyola-Chi': {'LSU': '47%',
  'Marquette': '45%',
  'Memphis': '46%',
  'Miami FL': '40%',
  'Michigan': '48%',
  'Michigan St': '50%',
  'Montana St': '66%',
  'Murray St': '50%',
  'N Mex St': '50%',
  'Norfolk St': '74%',
  'N Carolina': '49%',
  'Notre Dame': '53%',
  'Ohio St': '48%',
  'Providence': '50%',
  'Purdue': '28%',
  'Richmond': '38%',
  'Rutgers': '37%',
  'S Dakota St': '59%',
  'San Diego St': '47%',
  'San Fran': '45%',
  'Seton Hall': '52%',
  "St Mary's": '40%',
  "St Peter's": '57%',
  'TAM C. Christi': '76%',
  'TCU': '54%',
  'Tennessee': '34%',
  'Texas': '44%',
  'Texas Tech': '40%',
  'TX Southern': '69%',
  'UAB': '49%',
  'UCLA': '38%',
  'USC': '45%',
  'Vermont': '49%',
  'Villanova': '33%',
  'Virginia Tech': '38%',
  'Wisconsin': '49%',
  'Wright St': '65%',
  'Wyoming': '47%',
  'Yale': '61%',
  'Akron': '68%',
  'Alabama': '40%',
  'Arizona': '17%',
  'Arkansas': '29%',
  'Auburn': '13%',
  'Baylor': '20%',
  'Boise St': '31%',
  'Bryant': '66%',
  'Chatt': '53%',
  'Colgate': '61%',
  'Colo St': '27%',
  'Connecticut': '26%',
  'Creighton': '40%',
  'CS Fullerton': '71%',
  'Davidson': '44%',
  'Delaware': '63%',
  'Duke': '21%',
  'Georgia St': '70%',
  'Gonzaga': '16%',
  'Houston': '32%',
  'Illinois': '30%',
  'Indiana': '51%',
  'Iowa': '31%',
  'Iowa St': '49%',
  'Jville St': '71%',
  'Kansas': '15%',
  'Kentucky': '21%',
  'Longwood': '67%'},
 'LSU': {'Marquette': '50%',
  'Memphis': '62%',
  'Miami FL': '60%',
  'Michigan': '54%',
  'Michigan St': '41%',
  'Montana St': '80%',
  'Murray St': '56%',
  'N Mex St': '76%',
  'Norfolk St': '87%',
  'N Carolina': '52%',
  'Notre Dame': '60%',
  'Ohio St': '56%',
  'Providence': '51%',
  'Purdue': '47%',
  'Richmond': '58%',
  'Rutgers': '47%',
  'S Dakota St': '65%',
  'San Diego St': '49%',
  'San Fran': '61%',
  'Seton Hall': '54%',
  "St Mary's": '44%',
  "St Peter's": '81%',
  'TAM C. Christi': '91%',
  'TCU': '60%',
  'Tennessee': '34%',
  'Texas': '55%',
  'Texas Tech': '46%',
  'TX Southern': '89%',
  'UAB': '60%',
  'UCLA': '39%',
  'USC': '48%',
  'Vermont': '69%',
  'Villanova': '38%',
  'Virginia Tech': '51%',
  'Wisconsin': '49%',
  'Wright St': '83%',
  'Wyoming': '71%',
  'Yale': '86%',
  'Akron': '63%',
  'Alabama': '49%',
  'Arizona': '34%',
  'Arkansas': '52%',
  'Auburn': '39%',
  'Baylor': '30%',
  'Boise St': '46%',
  'Bryant': '65%',
  'Chatt': '54%',
  'Colgate': '56%',
  'Colo St': '52%',
  'Connecticut': '50%',
  'Creighton': '51%',
  'CS Fullerton': '67%',
  'Davidson': '56%',
  'Delaware': '64%',
  'Duke': '41%',
  'Georgia St': '69%',
  'Gonzaga': '31%',
  'Houston': '46%',
  'Illinois': '51%',
  'Indiana': '58%',
  'Iowa': '54%',
  'Iowa St': '63%',
  'Jville St': '64%',
  'Kansas': '23%',
  'Kentucky': '28%',
  'Longwood': '60%',
  'Loyola-Chi': '53%'},
 'Marquette': {'Memphis': '56%',
  'Miami FL': '51%',
  'Michigan': '50%',
  'Michigan St': '41%',
  'Montana St': '73%',
  'Murray St': '50%',
  'N Mex St': '69%',
  'Norfolk St': '78%',
  'N Carolina': '52%',
  'Notre Dame': '60%',
  'Ohio St': '55%',
  'Providence': '52%',
  'Purdue': '40%',
  'Richmond': '56%',
  'Rutgers': '50%',
  'S Dakota St': '72%',
  'San Diego St': '42%',
  'San Fran': '45%',
  'Seton Hall': '59%',
  "St Mary's": '34%',
  "St Peter's": '77%',
  'TAM C. Christi': '84%',
  'TCU': '58%',
  'Tennessee': '30%',
  'Texas': '55%',
  'Texas Tech': '45%',
  'TX Southern': '78%',
  'UAB': '60%',
  'UCLA': '43%',
  'USC': '50%',
  'Vermont': '72%',
  'Villanova': '36%',
  'Virginia Tech': '50%',
  'Wisconsin': '40%',
  'Wright St': '84%',
  'Wyoming': '74%',
  'Yale': '88%',
  'Akron': '68%',
  'Alabama': '45%',
  'Arizona': '43%',
  'Arkansas': '51%',
  'Auburn': '44%',
  'Baylor': '50%',
  'Boise St': '48%',
  'Bryant': '73%',
  'Chatt': '62%',
  'Colgate': '64%',
  'Colo St': '37%',
  'Connecticut': '51%',
  'Creighton': '51%',
  'CS Fullerton': '72%',
  'Davidson': '53%',
  'Delaware': '69%',
  'Duke': '49%',
  'Georgia St': '74%',
  'Gonzaga': '26%',
  'Houston': '50%',
  'Illinois': '52%',
  'Indiana': '58%',
  'Iowa': '58%',
  'Iowa St': '54%',
  'Jville St': '67%',
  'Kansas': '26%',
  'Kentucky': '31%',
  'Longwood': '68%',
  'Loyola-Chi': '55%',
  'LSU': '50%'},
 'Memphis': {'Miami FL': '55%',
  'Michigan': '46%',
  'Michigan St': '46%',
  'Montana St': '74%',
  'Murray St': '55%',
  'N Mex St': '80%',
  'Norfolk St': '79%',
  'N Carolina': '56%',
  'Notre Dame': '58%',
  'Ohio St': '54%',
  'Providence': '50%',
  'Purdue': '35%',
  'Richmond': '55%',
  'Rutgers': '48%',
  'S Dakota St': '63%',
  'San Diego St': '45%',
  'San Fran': '48%',
  'Seton Hall': '52%',
  "St Mary's": '37%',
  "St Peter's": '79%',
  'TAM C. Christi': '92%',
  'TCU': '51%',
  'Tennessee': '32%',
  'Texas': '52%',
  'Texas Tech': '41%',
  'TX Southern': '86%',
  'UAB': '61%',
  'UCLA': '38%',
  'USC': '55%',
  'Vermont': '61%',
  'Villanova': '29%',
  'Virginia Tech': '50%',
  'Wisconsin': '42%',
  'Wright St': '89%',
  'Wyoming': '76%',
  'Yale': '90%',
  'Akron': '66%',
  'Alabama': '32%',
  'Arizona': '37%',
  'Arkansas': '43%',
  'Auburn': '36%',
  'Baylor': '46%',
  'Boise St': '47%',
  'Bryant': '68%',
  'Chatt': '59%',
  'Colgate': '62%',
  'Colo St': '42%',
  'Connecticut': '43%',
  'Creighton': '48%',
  'CS Fullerton': '68%',
  'Davidson': '51%',
  'Delaware': '65%',
  'Duke': '41%',
  'Georgia St': '69%',
  'Gonzaga': '19%',
  'Houston': '41%',
  'Illinois': '49%',
  'Indiana': '57%',
  'Iowa': '46%',
  'Iowa St': '55%',
  'Jville St': '66%',
  'Kansas': '27%',
  'Kentucky': '26%',
  'Longwood': '65%',
  'Loyola-Chi': '54%',
  'LSU': '38%',
  'Marquette': '44%'},
 'Miami FL': {'Michigan': '42%',
  'Michigan St': '45%',
  'Montana St': '73%',
  'Murray St': '48%',
  'N Mex St': '59%',
  'Norfolk St': '80%',
  'N Carolina': '54%',
  'Notre Dame': '56%',
  'Ohio St': '39%',
  'Providence': '44%',
  'Purdue': '29%',
  'Richmond': '49%',
  'Rutgers': '47%',
  'S Dakota St': '56%',
  'San Diego St': '43%',
  'San Fran': '40%',
  'Seton Hall': '47%',
  "St Mary's": '35%',
  "St Peter's": '77%',
  'TAM C. Christi': '83%',
  'TCU': '45%',
  'Tennessee': '26%',
  'Texas': '44%',
  'Texas Tech': '40%',
  'TX Southern': '75%',
  'UAB': '56%',
  'UCLA': '36%',
  'USC': '49%',
  'Vermont': '57%',
  'Villanova': '24%',
  'Virginia Tech': '43%',
  'Wisconsin': '34%',
  'Wright St': '86%',
  'Wyoming': '56%',
  'Yale': '84%',
  'Akron': '67%',
  'Alabama': '32%',
  'Arizona': '15%',
  'Arkansas': '21%',
  'Auburn': '17%',
  'Baylor': '15%',
  'Boise St': '34%',
  'Bryant': '67%',
  'Chatt': '54%',
  'Colgate': '63%',
  'Colo St': '11%',
  'Connecticut': '27%',
  'Creighton': '44%',
  'CS Fullerton': '74%',
  'Davidson': '47%',
  'Delaware': '70%',
  'Duke': '40%',
  'Georgia St': '75%',
  'Gonzaga': '17%',
  'Houston': '47%',
  'Illinois': '26%',
  'Indiana': '46%',
  'Iowa': '47%',
  'Iowa St': '47%',
  'Jville St': '71%',
  'Kansas': '13%',
  'Kentucky': '14%',
  'Longwood': '67%',
  'Loyola-Chi': '60%',
  'LSU': '40%',
  'Marquette': '49%',
  'Memphis': '45%'},
 'Michigan': {'Michigan St': '44%',
  'Montana St': '72%',
  'Murray St': '49%',
  'N Mex St': '51%',
  'Norfolk St': '72%',
  'N Carolina': '52%',
  'Notre Dame': '48%',
  'Ohio St': '51%',
  'Providence': '52%',
  'Purdue': '44%',
  'Richmond': '43%',
  'Rutgers': '41%',
  'S Dakota St': '57%',
  'San Diego St': '44%',
  'San Fran': '45%',
  'Seton Hall': '52%',
  "St Mary's": '37%',
  "St Peter's": '69%',
  'TAM C. Christi': '69%',
  'TCU': '48%',
  'Tennessee': '38%',
  'Texas': '47%',
  'Texas Tech': '44%',
  'TX Southern': '70%',
  'UAB': '48%',
  'UCLA': '43%',
  'USC': '52%',
  'Vermont': '55%',
  'Villanova': '36%',
  'Virginia Tech': '44%',
  'Wisconsin': '47%',
  'Wright St': '75%',
  'Wyoming': '53%',
  'Yale': '78%',
  'Akron': '72%',
  'Alabama': '52%',
  'Arizona': '38%',
  'Arkansas': '44%',
  'Auburn': '41%',
  'Baylor': '41%',
  'Boise St': '38%',
  'Bryant': '66%',
  'Chatt': '59%',
  'Colgate': '68%',
  'Colo St': '40%',
  'Connecticut': '43%',
  'Creighton': '55%',
  'CS Fullerton': '71%',
  'Davidson': '56%',
  'Delaware': '68%',
  'Duke': '45%',
  'Georgia St': '66%',
  'Gonzaga': '22%',
  'Houston': '50%',
  'Illinois': '33%',
  'Indiana': '55%',
  'Iowa': '41%',
  'Iowa St': '57%',
  'Jville St': '70%',
  'Kansas': '27%',
  'Kentucky': '30%',
  'Longwood': '67%',
  'Loyola-Chi': '52%',
  'LSU': '46%',
  'Marquette': '50%',
  'Memphis': '54%',
  'Miami FL': '58%'},
 'Michigan St': {'Montana St': '75%',
  'Murray St': '53%',
  'N Mex St': '74%',
  'Norfolk St': '79%',
  'N Carolina': '60%',
  'Notre Dame': '83%',
  'Ohio St': '56%',
  'Providence': '56%',
  'Purdue': '47%',
  'Richmond': '65%',
  'Rutgers': '60%',
  'S Dakota St': '64%',
  'San Diego St': '53%',
  'San Fran': '68%',
  'Seton Hall': '55%',
  "St Mary's": '47%',
  "St Peter's": '76%',
  'TAM C. Christi': '82%',
  'TCU': '63%',
  'Tennessee': '34%',
  'Texas': '53%',
  'Texas Tech': '51%',
  'TX Southern': '83%',
  'UAB': '62%',
  'UCLA': '47%',
  'USC': '52%',
  'Vermont': '67%',
  'Villanova': '39%',
  'Virginia Tech': '64%',
  'Wisconsin': '54%',
  'Wright St': '90%',
  'Wyoming': '78%',
  'Yale': '93%',
  'Akron': '70%',
  'Alabama': '56%',
  'Arizona': '44%',
  'Arkansas': '54%',
  'Auburn': '46%',
  'Baylor': '53%',
  'Boise St': '53%',
  'Bryant': '70%',
  'Chatt': '60%',
  'Colgate': '69%',
  'Colo St': '48%',
  'Connecticut': '60%',
  'Creighton': '51%',
  'CS Fullerton': '76%',
  'Davidson': '51%',
  'Delaware': '72%',
  'Duke': '51%',
  'Georgia St': '73%',
  'Gonzaga': '27%',
  'Houston': '52%',
  'Illinois': '61%',
  'Indiana': '60%',
  'Iowa': '55%',
  'Iowa St': '59%',
  'Jville St': '74%',
  'Kansas': '45%',
  'Kentucky': '41%',
  'Longwood': '68%',
  'Loyola-Chi': '50%',
  'LSU': '59%',
  'Marquette': '59%',
  'Memphis': '54%',
  'Miami FL': '55%',
  'Michigan': '56%'},
 'Montana St': {'Murray St': '34%',
  'N Mex St': '31%',
  'Norfolk St': '52%',
  'N Carolina': '29%',
  'Notre Dame': '32%',
  'Ohio St': '31%',
  'Providence': '29%',
  'Purdue': '23%',
  'Richmond': '33%',
  'Rutgers': '26%',
  'S Dakota St': '31%',
  'San Diego St': '28%',
  'San Fran': '29%',
  'Seton Hall': '34%',
  "St Mary's": '26%',
  "St Peter's": '43%',
  'TAM C. Christi': '51%',
  'TCU': '33%',
  'Tennessee': '30%',
  'Texas': '37%',
  'Texas Tech': '30%',
  'TX Southern': '48%',
  'UAB': '34%',
  'UCLA': '26%',
  'USC': '29%',
  'Vermont': '43%',
  'Villanova': '24%',
  'Virginia Tech': '32%',
  'Wisconsin': '28%',
  'Wright St': '46%',
  'Wyoming': '29%',
  'Yale': '46%',
  'Akron': '46%',
  'Alabama': '27%',
  'Arizona': '1%',
  'Arkansas': '14%',
  'Auburn': '6%',
  'Baylor': '1%',
  'Boise St': '11%',
  'Bryant': '59%',
  'Chatt': '51%',
  'Colgate': '51%',
  'Colo St': '15%',
  'Connecticut': '17%',
  'Creighton': '27%',
  'CS Fullerton': '50%',
  'Davidson': '18%',
  'Delaware': '48%',
  'Duke': '12%',
  'Georgia St': '50%',
  'Gonzaga': '1%',
  'Houston': '29%',
  'Illinois': '20%',
  'Indiana': '42%',
  'Iowa': '21%',
  'Iowa St': '25%',
  'Jville St': '55%',
  'Kansas': '1%',
  'Kentucky': '13%',
  'Longwood': '59%',
  'Loyola-Chi': '34%',
  'LSU': '20%',
  'Marquette': '27%',
  'Memphis': '26%',
  'Miami FL': '27%',
  'Michigan': '28%',
  'Michigan St': '25%'},
 'Murray St': {'N Mex St': '50%',
  'Norfolk St': '75%',
  'N Carolina': '49%',
  'Notre Dame': '61%',
  'Ohio St': '52%',
  'Providence': '56%',
  'Purdue': '44%',
  'Richmond': '38%',
  'Rutgers': '44%',
  'S Dakota St': '51%',
  'San Diego St': '48%',
  'San Fran': '42%',
  'Seton Hall': '53%',
  "St Mary's": '44%',
  "St Peter's": '59%',
  'TAM C. Christi': '79%',
  'TCU': '53%',
  'Tennessee': '34%',
  'Texas': '47%',
  'Texas Tech': '40%',
  'TX Southern': '74%',
  'UAB': '50%',
  'UCLA': '42%',
  'USC': '47%',
  'Vermont': '53%',
  'Villanova': '34%',
  'Virginia Tech': '44%',
  'Wisconsin': '51%',
  'Wright St': '68%',
  'Wyoming': '53%',
  'Yale': '63%',
  'Akron': '68%',
  'Alabama': '47%',
  'Arizona': '14%',
  'Arkansas': '27%',
  'Auburn': '15%',
  'Baylor': '19%',
  'Boise St': '40%',
  'Bryant': '72%',
  'Chatt': '50%',
  'Colgate': '69%',
  'Colo St': '47%',
  'Connecticut': '43%',
  'Creighton': '51%',
  'CS Fullerton': '72%',
  'Davidson': '41%',
  'Delaware': '61%',
  'Duke': '33%',
  'Georgia St': '68%',
  'Gonzaga': '19%',
  'Houston': '48%',
  'Illinois': '36%',
  'Indiana': '54%',
  'Iowa': '43%',
  'Iowa St': '53%',
  'Jville St': '70%',
  'Kansas': '17%',
  'Kentucky': '25%',
  'Longwood': '75%',
  'Loyola-Chi': '50%',
  'LSU': '44%',
  'Marquette': '50%',
  'Memphis': '45%',
  'Miami FL': '52%',
  'Michigan': '51%',
  'Michigan St': '47%',
  'Montana St': '66%'},
 'N Mex St': {'Norfolk St': '59%',
  'N Carolina': '34%',
  'Notre Dame': '43%',
  'Ohio St': '31%',
  'Providence': '32%',
  'Purdue': '25%',
  'Richmond': '45%',
  'Rutgers': '37%',
  'S Dakota St': '44%',
  'San Diego St': '35%',
  'San Fran': '29%',
  'Seton Hall': '36%',
  "St Mary's": '33%',
  "St Peter's": '57%',
  'TAM C. Christi': '67%',
  'TCU': '33%',
  'Tennessee': '25%',
  'Texas': '34%',
  'Texas Tech': '33%',
  'TX Southern': '57%',
  'UAB': '41%',
  'UCLA': '35%',
  'USC': '36%',
  'Vermont': '43%',
  'Villanova': '23%',
  'Virginia Tech': '33%',
  'Wisconsin': '33%',
  'Wright St': '55%',
  'Wyoming': '44%',
  'Yale': '55%',
  'Akron': '62%',
  'Alabama': '33%',
  'Arizona': '7%',
  'Arkansas': '20%',
  'Auburn': '15%',
  'Baylor': '17%',
  'Boise St': '14%',
  'Bryant': '59%',
  'Chatt': '50%',
  'Colgate': '59%',
  'Colo St': '23%',
  'Connecticut': '14%',
  'Creighton': '20%',
  'CS Fullerton': '68%',
  'Davidson': '42%',
  'Delaware': '61%',
  'Duke': '26%',
  'Georgia St': '68%',
  'Gonzaga': '15%',
  'Houston': '33%',
  'Illinois': '21%',
  'Indiana': '43%',
  'Iowa': '20%',
  'Iowa St': '38%',
  'Jville St': '70%',
  'Kansas': '14%',
  'Kentucky': '19%',
  'Longwood': '63%',
  'Loyola-Chi': '50%',
  'LSU': '24%',
  'Marquette': '31%',
  'Memphis': '20%',
  'Miami FL': '41%',
  'Michigan': '49%',
  'Michigan St': '26%',
  'Montana St': '69%',
  'Murray St': '50%'},
 'Norfolk St': {'N Carolina': '26%',
  'Notre Dame': '31%',
  'Ohio St': '30%',
  'Providence': '24%',
  'Purdue': '9%',
  'Richmond': '29%',
  'Rutgers': '28%',
  'S Dakota St': '30%',
  'San Diego St': '29%',
  'San Fran': '27%',
  'Seton Hall': '31%',
  "St Mary's": '24%',
  "St Peter's": '41%',
  'TAM C. Christi': '48%',
  'TCU': '27%',
  'Tennessee': '9%',
  'Texas': '32%',
  'Texas Tech': '11%',
  'TX Southern': '42%',
  'UAB': '27%',
  'UCLA': '21%',
  'USC': '23%',
  'Vermont': '28%',
  'Villanova': '5%',
  'Virginia Tech': '28%',
  'Wisconsin': '9%',
  'Wright St': '38%',
  'Wyoming': '28%',
  'Yale': '46%',
  'Akron': '35%',
  'Alabama': '22%',
  'Arizona': '1%',
  'Arkansas': '19%',
  'Auburn': '1%',
  'Baylor': '1%',
  'Boise St': '11%',
  'Bryant': '50%',
  'Chatt': '31%',
  'Colgate': '47%',
  'Colo St': '16%',
  'Connecticut': '14%',
  'Creighton': '18%',
  'CS Fullerton': '54%',
  'Davidson': '14%',
  'Delaware': '42%',
  'Duke': '1%',
  'Georgia St': '50%',
  'Gonzaga': '1%',
  'Houston': '24%',
  'Illinois': '22%',
  'Indiana': '24%',
  'Iowa': '20%',
  'Iowa St': '13%',
  'Jville St': '42%',
  'Kansas': '1%',
  'Kentucky': '1%',
  'Longwood': '50%',
  'Loyola-Chi': '26%',
  'LSU': '13%',
  'Marquette': '22%',
  'Memphis': '21%',
  'Miami FL': '20%',
  'Michigan': '28%',
  'Michigan St': '21%',
  'Montana St': '48%',
  'Murray St': '25%',
  'N Mex St': '41%'},
 'N Carolina': {'Notre Dame': '62%',
  'Ohio St': '44%',
  'Providence': '48%',
  'Purdue': '35%',
  'Richmond': '40%',
  'Rutgers': '46%',
  'S Dakota St': '54%',
  'San Diego St': '40%',
  'San Fran': '38%',
  'Seton Hall': '50%',
  "St Mary's": '35%',
  "St Peter's": '69%',
  'TAM C. Christi': '68%',
  'TCU': '45%',
  'Tennessee': '36%',
  'Texas': '48%',
  'Texas Tech': '39%',
  'TX Southern': '74%',
  'UAB': '53%',
  'UCLA': '37%',
  'USC': '51%',
  'Vermont': '56%',
  'Villanova': '34%',
  'Virginia Tech': '55%',
  'Wisconsin': '43%',
  'Wright St': '68%',
  'Wyoming': '66%',
  'Yale': '70%',
  'Akron': '68%',
  'Alabama': '45%',
  'Arizona': '21%',
  'Arkansas': '29%',
  'Auburn': '11%',
  'Baylor': '15%',
  'Boise St': '35%',
  'Bryant': '73%',
  'Chatt': '55%',
  'Colgate': '66%',
  'Colo St': '37%',
  'Connecticut': '24%',
  'Creighton': '39%',
  'CS Fullerton': '72%',
  'Davidson': '48%',
  'Delaware': '73%',
  'Duke': '37%',
  'Georgia St': '71%',
  'Gonzaga': '13%',
  'Houston': '33%',
  'Illinois': '21%',
  'Indiana': '62%',
  'Iowa': '42%',
  'Iowa St': '58%',
  'Jville St': '72%',
  'Kansas': '8%',
  'Kentucky': '8%',
  'Longwood': '69%',
  'Loyola-Chi': '51%',
  'LSU': '48%',
  'Marquette': '48%',
  'Memphis': '44%',
  'Miami FL': '46%',
  'Michigan': '48%',
  'Michigan St': '40%',
  'Montana St': '71%',
  'Murray St': '51%',
  'N Mex St': '66%',
  'Norfolk St': '74%'},
 'Notre Dame': {'Ohio St': '36%',
  'Providence': '28%',
  'Purdue': '26%',
  'Richmond': '44%',
  'Rutgers': '46%',
  'S Dakota St': '49%',
  'San Diego St': '39%',
  'San Fran': '40%',
  'Seton Hall': '44%',
  "St Mary's": '26%',
  "St Peter's": '64%',
  'TAM C. Christi': '69%',
  'TCU': '43%',
  'Tennessee': '24%',
  'Texas': '37%',
  'Texas Tech': '26%',
  'TX Southern': '68%',
  'UAB': '47%',
  'UCLA': '27%',
  'USC': '40%',
  'Vermont': '50%',
  'Villanova': '20%',
  'Virginia Tech': '42%',
  'Wisconsin': '26%',
  'Wright St': '65%',
  'Wyoming': '47%',
  'Yale': '73%',
  'Akron': '69%',
  'Alabama': '34%',
  'Arizona': '8%',
  'Arkansas': '21%',
  'Auburn': '18%',
  'Baylor': '13%',
  'Boise St': '1%',
  'Bryant': '68%',
  'Chatt': '50%',
  'Colgate': '63%',
  'Colo St': '1%',
  'Connecticut': '21%',
  'Creighton': '37%',
  'CS Fullerton': '70%',
  'Davidson': '40%',
  'Delaware': '68%',
  'Duke': '25%',
  'Georgia St': '74%',
  'Gonzaga': '8%',
  'Houston': '39%',
  'Illinois': '20%',
  'Indiana': '42%',
  'Iowa': '39%',
  'Iowa St': '36%',
  'Jville St': '68%',
  'Kansas': '12%',
  'Kentucky': '9%',
  'Longwood': '70%',
  'Loyola-Chi': '47%',
  'LSU': '40%',
  'Marquette': '40%',
  'Memphis': '42%',
  'Miami FL': '44%',
  'Michigan': '52%',
  'Michigan St': '17%',
  'Montana St': '68%',
  'Murray St': '39%',
  'N Mex St': '57%',
  'Norfolk St': '69%',
  'N Carolina': '38%'},
 'Ohio St': {'Providence': '45%',
  'Purdue': '32%',
  'Richmond': '61%',
  'Rutgers': '45%',
  'S Dakota St': '65%',
  'San Diego St': '34%',
  'San Fran': '32%',
  'Seton Hall': '56%',
  "St Mary's": '29%',
  "St Peter's": '73%',
  'TAM C. Christi': '80%',
  'TCU': '48%',
  'Tennessee': '30%',
  'Texas': '51%',
  'Texas Tech': '40%',
  'TX Southern': '80%',
  'UAB': '50%',
  'UCLA': '31%',
  'USC': '51%',
  'Vermont': '66%',
  'Villanova': '29%',
  'Virginia Tech': '58%',
  'Wisconsin': '41%',
  'Wright St': '82%',
  'Wyoming': '70%',
  'Yale': '83%',
  'Akron': '70%',
  'Alabama': '46%',
  'Arizona': '35%',
  'Arkansas': '37%',
  'Auburn': '29%',
  'Baylor': '24%',
  'Boise St': '44%',
  'Bryant': '67%',
  'Chatt': '63%',
  'Colgate': '62%',
  'Colo St': '51%',
  'Connecticut': '44%',
  'Creighton': '46%',
  'CS Fullerton': '69%',
  'Davidson': '55%',
  'Delaware': '68%',
  'Duke': '35%',
  'Georgia St': '72%',
  'Gonzaga': '17%',
  'Houston': '47%',
  'Illinois': '24%',
  'Indiana': '57%',
  'Iowa': '49%',
  'Iowa St': '52%',
  'Jville St': '67%',
  'Kansas': '22%',
  'Kentucky': '24%',
  'Longwood': '65%',
  'Loyola-Chi': '52%',
  'LSU': '44%',
  'Marquette': '45%',
  'Memphis': '46%',
  'Miami FL': '61%',
  'Michigan': '49%',
  'Michigan St': '44%',
  'Montana St': '69%',
  'Murray St': '48%',
  'N Mex St': '69%',
  'Norfolk St': '70%',
  'N Carolina': '56%',
  'Notre Dame': '64%'},
 'Providence': {'Purdue': '40%',
  'Richmond': '67%',
  'Rutgers': '55%',
  'S Dakota St': '65%',
  'San Diego St': '43%',
  'San Fran': '49%',
  'Seton Hall': '61%',
  "St Mary's": '38%',
  "St Peter's": '79%',
  'TAM C. Christi': '82%',
  'TCU': '56%',
  'Tennessee': '37%',
  'Texas': '50%',
  'Texas Tech': '43%',
  'TX Southern': '81%',
  'UAB': '65%',
  'UCLA': '43%',
  'USC': '73%',
  'Vermont': '67%',
  'Villanova': '37%',
  'Virginia Tech': '71%',
  'Wisconsin': '41%',
  'Wright St': '85%',
  'Wyoming': '75%',
  'Yale': '87%',
  'Akron': '74%',
  'Alabama': '48%',
  'Arizona': '39%',
  'Arkansas': '47%',
  'Auburn': '41%',
  'Baylor': '33%',
  'Boise St': '41%',
  'Bryant': '72%',
  'Chatt': '61%',
  'Colgate': '70%',
  'Colo St': '42%',
  'Connecticut': '42%',
  'Creighton': '47%',
  'CS Fullerton': '75%',
  'Davidson': '55%',
  'Delaware': '75%',
  'Duke': '44%',
  'Georgia St': '72%',
  'Gonzaga': '27%',
  'Houston': '47%',
  'Illinois': '45%',
  'Indiana': '60%',
  'Iowa': '47%',
  'Iowa St': '58%',
  'Jville St': '75%',
  'Kansas': '24%',
  'Kentucky': '42%',
  'Longwood': '69%',
  'Loyola-Chi': '50%',
  'LSU': '49%',
  'Marquette': '48%',
  'Memphis': '50%',
  'Miami FL': '56%',
  'Michigan': '48%',
  'Michigan St': '44%',
  'Montana St': '71%',
  'Murray St': '44%',
  'N Mex St': '68%',
  'Norfolk St': '76%',
  'N Carolina': '52%',
  'Notre Dame': '72%',
  'Ohio St': '55%'},
 'Purdue': {'Richmond': '76%',
  'Rutgers': '68%',
  'S Dakota St': '80%',
  'San Diego St': '62%',
  'San Fran': '70%',
  'Seton Hall': '80%',
  "St Mary's": '47%',
  "St Peter's": '78%',
  'TAM C. Christi': '93%',
  'TCU': '78%',
  'Tennessee': '48%',
  'Texas': '75%',
  'Texas Tech': '50%',
  'TX Southern': '91%',
  'UAB': '70%',
  'UCLA': '50%',
  'USC': '73%',
  'Vermont': '74%',
  'Villanova': '43%',
  'Virginia Tech': '74%',
  'Wisconsin': '56%',
  'Wright St': '97%',
  'Wyoming': '80%',
  'Yale': '85%',
  'Akron': '79%',
  'Alabama': '52%',
  'Arizona': '45%',
  'Arkansas': '61%',
  'Auburn': '52%',
  'Baylor': '50%',
  'Boise St': '55%',
  'Bryant': '86%',
  'Chatt': '66%',
  'Colgate': '74%',
  'Colo St': '60%',
  'Connecticut': '62%',
  'Creighton': '61%',
  'CS Fullerton': '77%',
  'Davidson': '62%',
  'Delaware': '78%',
  'Duke': '52%',
  'Georgia St': '83%',
  'Gonzaga': '42%',
  'Houston': '50%',
  'Illinois': '60%',
  'Indiana': '74%',
  'Iowa': '53%',
  'Iowa St': '68%',
  'Jville St': '78%',
  'Kansas': '45%',
  'Kentucky': '45%',
  'Longwood': '75%',
  'Loyola-Chi': '72%',
  'LSU': '53%',
  'Marquette': '60%',
  'Memphis': '65%',
  'Miami FL': '71%',
  'Michigan': '56%',
  'Michigan St': '53%',
  'Montana St': '77%',
  'Murray St': '56%',
  'N Mex St': '75%',
  'Norfolk St': '91%',
  'N Carolina': '65%',
  'Notre Dame': '74%',
  'Ohio St': '68%',
  'Providence': '60%'},
 'Richmond': {'Rutgers': '45%',
  'S Dakota St': '46%',
  'San Diego St': '43%',
  'San Fran': '42%',
  'Seton Hall': '51%',
  "St Mary's": '38%',
  "St Peter's": '75%',
  'TAM C. Christi': '86%',
  'TCU': '46%',
  'Tennessee': '29%',
  'Texas': '48%',
  'Texas Tech': '45%',
  'TX Southern': '75%',
  'UAB': '48%',
  'UCLA': '38%',
  'USC': '48%',
  'Vermont': '50%',
  'Villanova': '26%',
  'Virginia Tech': '45%',
  'Wisconsin': '41%',
  'Wright St': '81%',
  'Wyoming': '59%',
  'Yale': '65%',
  'Akron': '65%',
  'Alabama': '40%',
  'Arizona': '25%',
  'Arkansas': '35%',
  'Auburn': '25%',
  'Baylor': '30%',
  'Boise St': '27%',
  'Bryant': '68%',
  'Chatt': '51%',
  'Colgate': '66%',
  'Colo St': '37%',
  'Connecticut': '36%',
  'Creighton': '39%',
  'CS Fullerton': '72%',
  'Davidson': '55%',
  'Delaware': '68%',
  'Duke': '45%',
  'Georgia St': '77%',
  'Gonzaga': '19%',
  'Houston': '49%',
  'Illinois': '31%',
  'Indiana': '58%',
  'Iowa': '30%',
  'Iowa St': '51%',
  'Jville St': '72%',
  'Kansas': '16%',
  'Kentucky': '29%',
  'Longwood': '63%',
  'Loyola-Chi': '62%',
  'LSU': '42%',
  'Marquette': '44%',
  'Memphis': '45%',
  'Miami FL': '51%',
  'Michigan': '57%',
  'Michigan St': '35%',
  'Montana St': '67%',
  'Murray St': '62%',
  'N Mex St': '55%',
  'Norfolk St': '71%',
  'N Carolina': '60%',
  'Notre Dame': '56%',
  'Ohio St': '39%',
  'Providence': '33%',
  'Purdue': '24%'},
 'Rutgers': {'S Dakota St': '53%',
  'San Diego St': '36%',
  'San Fran': '33%',
  'Seton Hall': '50%',
  "St Mary's": '30%',
  "St Peter's": '85%',
  'TAM C. Christi': '86%',
  'TCU': '46%',
  'Tennessee': '27%',
  'Texas': '39%',
  'Texas Tech': '33%',
  'TX Southern': '80%',
  'UAB': '51%',
  'UCLA': '36%',
  'USC': '49%',
  'Vermont': '55%',
  'Villanova': '33%',
  'Virginia Tech': '42%',
  'Wisconsin': '33%',
  'Wright St': '81%',
  'Wyoming': '50%',
  'Yale': '96%',
  'Akron': '73%',
  'Alabama': '43%',
  'Arizona': '34%',
  'Arkansas': '41%',
  'Auburn': '33%',
  'Baylor': '36%',
  'Boise St': '43%',
  'Bryant': '69%',
  'Chatt': '55%',
  'Colgate': '71%',
  'Colo St': '33%',
  'Connecticut': '46%',
  'Creighton': '42%',
  'CS Fullerton': '75%',
  'Davidson': '55%',
  'Delaware': '73%',
  'Duke': '45%',
  'Georgia St': '75%',
  'Gonzaga': '16%',
  'Houston': '42%',
  'Illinois': '49%',
  'Indiana': '52%',
  'Iowa': '46%',
  'Iowa St': '46%',
  'Jville St': '74%',
  'Kansas': '32%',
  'Kentucky': '35%',
  'Longwood': '70%',
  'Loyola-Chi': '63%',
  'LSU': '53%',
  'Marquette': '50%',
  'Memphis': '52%',
  'Miami FL': '53%',
  'Michigan': '59%',
  'Michigan St': '40%',
  'Montana St': '74%',
  'Murray St': '56%',
  'N Mex St': '63%',
  'Norfolk St': '72%',
  'N Carolina': '54%',
  'Notre Dame': '54%',
  'Ohio St': '55%',
  'Providence': '45%',
  'Purdue': '32%',
  'Richmond': '55%'},
 'S Dakota St': {'San Diego St': '36%',
  'San Fran': '33%',
  'Seton Hall': '38%',
  "St Mary's": '34%',
  "St Peter's": '46%',
  'TAM C. Christi': '70%',
  'TCU': '36%',
  'Tennessee': '34%',
  'Texas': '33%',
  'Texas Tech': '34%',
  'TX Southern': '64%',
  'UAB': '38%',
  'UCLA': '33%',
  'USC': '36%',
  'Vermont': '46%',
  'Villanova': '33%',
  'Virginia Tech': '36%',
  'Wisconsin': '35%',
  'Wright St': '60%',
  'Wyoming': '47%',
  'Yale': '44%',
  'Akron': '60%',
  'Alabama': '32%',
  'Arizona': '8%',
  'Arkansas': '33%',
  'Auburn': '20%',
  'Baylor': '21%',
  'Boise St': '32%',
  'Bryant': '63%',
  'Chatt': '47%',
  'Colgate': '63%',
  'Colo St': '33%',
  'Connecticut': '38%',
  'Creighton': '42%',
  'CS Fullerton': '66%',
  'Davidson': '33%',
  'Delaware': '55%',
  'Duke': '17%',
  'Georgia St': '60%',
  'Gonzaga': '18%',
  'Houston': '38%',
  'Illinois': '39%',
  'Indiana': '45%',
  'Iowa': '30%',
  'Iowa St': '47%',
  'Jville St': '63%',
  'Kansas': '16%',
  'Kentucky': '17%',
  'Longwood': '66%',
  'Loyola-Chi': '41%',
  'LSU': '35%',
  'Marquette': '28%',
  'Memphis': '37%',
  'Miami FL': '44%',
  'Michigan': '43%',
  'Michigan St': '36%',
  'Montana St': '69%',
  'Murray St': '49%',
  'N Mex St': '56%',
  'Norfolk St': '70%',
  'N Carolina': '46%',
  'Notre Dame': '51%',
  'Ohio St': '35%',
  'Providence': '35%',
  'Purdue': '20%',
  'Richmond': '54%',
  'Rutgers': '47%'},
 'San Diego St': {'San Fran': '48%',
  'Seton Hall': '62%',
  "St Mary's": '49%',
  "St Peter's": '91%',
  'TAM C. Christi': '93%',
  'TCU': '61%',
  'Tennessee': '32%',
  'Texas': '61%',
  'Texas Tech': '51%',
  'TX Southern': '88%',
  'UAB': '60%',
  'UCLA': '49%',
  'USC': '54%',
  'Vermont': '67%',
  'Villanova': '34%',
  'Virginia Tech': '67%',
  'Wisconsin': '51%',
  'Wright St': '88%',
  'Wyoming': '77%',
  'Yale': '89%',
  'Akron': '73%',
  'Alabama': '44%',
  'Arizona': '42%',
  'Arkansas': '51%',
  'Auburn': '46%',
  'Baylor': '36%',
  'Boise St': '48%',
  'Bryant': '67%',
  'Chatt': '58%',
  'Colgate': '62%',
  'Colo St': '56%',
  'Connecticut': '45%',
  'Creighton': '50%',
  'CS Fullerton': '77%',
  'Davidson': '55%',
  'Delaware': '69%',
  'Duke': '44%',
  'Georgia St': '77%',
  'Gonzaga': '31%',
  'Houston': '44%',
  'Illinois': '43%',
  'Indiana': '68%',
  'Iowa': '44%',
  'Iowa St': '66%',
  'Jville St': '72%',
  'Kansas': '19%',
  'Kentucky': '34%',
  'Longwood': '70%',
  'Loyola-Chi': '53%',
  'LSU': '51%',
  'Marquette': '58%',
  'Memphis': '55%',
  'Miami FL': '57%',
  'Michigan': '56%',
  'Michigan St': '47%',
  'Montana St': '72%',
  'Murray St': '52%',
  'N Mex St': '65%',
  'Norfolk St': '71%',
  'N Carolina': '60%',
  'Notre Dame': '61%',
  'Ohio St': '66%',
  'Providence': '57%',
  'Purdue': '38%',
  'Richmond': '57%',
  'Rutgers': '64%',
  'S Dakota St': '64%'},
 'San Fran': {'Seton Hall': '61%',
  "St Mary's": '49%',
  "St Peter's": '76%',
  'TAM C. Christi': '85%',
  'TCU': '55%',
  'Tennessee': '37%',
  'Texas': '56%',
  'Texas Tech': '49%',
  'TX Southern': '72%',
  'UAB': '48%',
  'UCLA': '46%',
  'USC': '55%',
  'Vermont': '58%',
  'Villanova': '34%',
  'Virginia Tech': '53%',
  'Wisconsin': '50%',
  'Wright St': '79%',
  'Wyoming': '52%',
  'Yale': '81%',
  'Akron': '72%',
  'Alabama': '43%',
  'Arizona': '33%',
  'Arkansas': '52%',
  'Auburn': '29%',
  'Baylor': '28%',
  'Boise St': '51%',
  'Bryant': '70%',
  'Chatt': '60%',
  'Colgate': '67%',
  'Colo St': '52%',
  'Connecticut': '34%',
  'Creighton': '44%',
  'CS Fullerton': '77%',
  'Davidson': '56%',
  'Delaware': '73%',
  'Duke': '40%',
  'Georgia St': '76%',
  'Gonzaga': '26%',
  'Houston': '43%',
  'Illinois': '35%',
  'Indiana': '67%',
  'Iowa': '44%',
  'Iowa St': '64%',
  'Jville St': '74%',
  'Kansas': '11%',
  'Kentucky': '27%',
  'Longwood': '72%',
  'Loyola-Chi': '55%',
  'LSU': '39%',
  'Marquette': '55%',
  'Memphis': '52%',
  'Miami FL': '60%',
  'Michigan': '55%',
  'Michigan St': '32%',
  'Montana St': '71%',
  'Murray St': '58%',
  'N Mex St': '71%',
  'Norfolk St': '73%',
  'N Carolina': '62%',
  'Notre Dame': '60%',
  'Ohio St': '68%',
  'Providence': '51%',
  'Purdue': '30%',
  'Richmond': '58%',
  'Rutgers': '67%',
  'S Dakota St': '67%',
  'San Diego St': '52%'},
 'Seton Hall': {"St Mary's": '34%',
  "St Peter's": '79%',
  'TAM C. Christi': '86%',
  'TCU': '48%',
  'Tennessee': '30%',
  'Texas': '53%',
  'Texas Tech': '38%',
  'TX Southern': '79%',
  'UAB': '49%',
  'UCLA': '36%',
  'USC': '53%',
  'Vermont': '60%',
  'Villanova': '27%',
  'Virginia Tech': '53%',
  'Wisconsin': '35%',
  'Wright St': '72%',
  'Wyoming': '66%',
  'Yale': '81%',
  'Akron': '65%',
  'Alabama': '44%',
  'Arizona': '31%',
  'Arkansas': '38%',
  'Auburn': '19%',
  'Baylor': '23%',
  'Boise St': '40%',
  'Bryant': '68%',
  'Chatt': '62%',
  'Colgate': '62%',
  'Colo St': '43%',
  'Connecticut': '26%',
  'Creighton': '46%',
  'CS Fullerton': '70%',
  'Davidson': '53%',
  'Delaware': '66%',
  'Duke': '34%',
  'Georgia St': '71%',
  'Gonzaga': '19%',
  'Houston': '30%',
  'Illinois': '27%',
  'Indiana': '49%',
  'Iowa': '43%',
  'Iowa St': '44%',
  'Jville St': '66%',
  'Kansas': '22%',
  'Kentucky': '27%',
  'Longwood': '65%',
  'Loyola-Chi': '48%',
  'LSU': '46%',
  'Marquette': '41%',
  'Memphis': '48%',
  'Miami FL': '53%',
  'Michigan': '48%',
  'Michigan St': '45%',
  'Montana St': '66%',
  'Murray St': '47%',
  'N Mex St': '64%',
  'Norfolk St': '69%',
  'N Carolina': '50%',
  'Notre Dame': '56%',
  'Ohio St': '44%',
  'Providence': '39%',
  'Purdue': '20%',
  'Richmond': '49%',
  'Rutgers': '50%',
  'S Dakota St': '62%',
  'San Diego St': '38%',
  'San Fran': '39%'},
 "St Mary's": {"St Peter's": '86%',
  'TAM C. Christi': '88%',
  'TCU': '73%',
  'Tennessee': '51%',
  'Texas': '64%',
  'Texas Tech': '51%',
  'TX Southern': '95%',
  'UAB': '65%',
  'UCLA': '56%',
  'USC': '54%',
  'Vermont': '71%',
  'Villanova': '47%',
  'Virginia Tech': '61%',
  'Wisconsin': '56%',
  'Wright St': '91%',
  'Wyoming': '71%',
  'Yale': '90%',
  'Akron': '74%',
  'Alabama': '59%',
  'Arizona': '46%',
  'Arkansas': '63%',
  'Auburn': '52%',
  'Baylor': '43%',
  'Boise St': '52%',
  'Bryant': '75%',
  'Chatt': '65%',
  'Colgate': '69%',
  'Colo St': '58%',
  'Connecticut': '56%',
  'Creighton': '56%',
  'CS Fullerton': '80%',
  'Davidson': '64%',
  'Delaware': '77%',
  'Duke': '44%',
  'Georgia St': '76%',
  'Gonzaga': '38%',
  'Houston': '53%',
  'Illinois': '55%',
  'Indiana': '72%',
  'Iowa': '50%',
  'Iowa St': '74%',
  'Jville St': '79%',
  'Kansas': '41%',
  'Kentucky': '31%',
  'Longwood': '74%',
  'Loyola-Chi': '60%',
  'LSU': '56%',
  'Marquette': '66%',
  'Memphis': '63%',
  'Miami FL': '65%',
  'Michigan': '63%',
  'Michigan St': '53%',
  'Montana St': '74%',
  'Murray St': '56%',
  'N Mex St': '67%',
  'Norfolk St': '76%',
  'N Carolina': '65%',
  'Notre Dame': '74%',
  'Ohio St': '71%',
  'Providence': '62%',
  'Purdue': '53%',
  'Richmond': '62%',
  'Rutgers': '70%',
  'S Dakota St': '66%',
  'San Diego St': '51%',
  'San Fran': '51%',
  'Seton Hall': '66%'},
 "St Peter's": {'TAM C. Christi': '51%',
  'TCU': '25%',
  'Tennessee': '19%',
  'Texas': '26%',
  'Texas Tech': '18%',
  'TX Southern': '49%',
  'UAB': '32%',
  'UCLA': '21%',
  'USC': '27%',
  'Vermont': '40%',
  'Villanova': '9%',
  'Virginia Tech': '25%',
  'Wisconsin': '20%',
  'Wright St': '42%',
  'Wyoming': '28%',
  'Yale': '42%',
  'Akron': '49%',
  'Alabama': '23%',
  'Arizona': '1%',
  'Arkansas': '16%',
  'Auburn': '2%',
  'Baylor': '1%',
  'Boise St': '15%',
  'Bryant': '55%',
  'Chatt': '44%',
  'Colgate': '47%',
  'Colo St': '20%',
  'Connecticut': '17%',
  'Creighton': '19%',
  'CS Fullerton': '58%',
  'Davidson': '28%',
  'Delaware': '48%',
  'Duke': '8%',
  'Georgia St': '59%',
  'Gonzaga': '1%',
  'Houston': '29%',
  'Illinois': '22%',
  'Indiana': '27%',
  'Iowa': '27%',
  'Iowa St': '15%',
  'Jville St': '51%',
  'Kansas': '1%',
  'Kentucky': '1%',
  'Longwood': '50%',
  'Loyola-Chi': '43%',
  'LSU': '19%',
  'Marquette': '23%',
  'Memphis': '21%',
  'Miami FL': '23%',
  'Michigan': '31%',
  'Michigan St': '24%',
  'Montana St': '57%',
  'Murray St': '41%',
  'N Mex St': '43%',
  'Norfolk St': '59%',
  'N Carolina': '31%',
  'Notre Dame': '36%',
  'Ohio St': '27%',
  'Providence': '21%',
  'Purdue': '22%',
  'Richmond': '25%',
  'Rutgers': '15%',
  'S Dakota St': '54%',
  'San Diego St': '9%',
  'San Fran': '24%',
  'Seton Hall': '21%',
  "St Mary's": '14%'},
 'TAM C. Christi': {'TCU': '28%',
  'Tennessee': '8%',
  'Texas': '29%',
  'Texas Tech': '8%',
  'TX Southern': '40%',
  'UAB': '24%',
  'UCLA': '21%',
  'USC': '25%',
  'Vermont': '32%',
  'Villanova': '5%',
  'Virginia Tech': '28%',
  'Wisconsin': '10%',
  'Wright St': '35%',
  'Wyoming': '25%',
  'Yale': '34%',
  'Akron': '40%',
  'Alabama': '20%',
  'Arizona': '1%',
  'Arkansas': '12%',
  'Auburn': '1%',
  'Baylor': '1%',
  'Boise St': '8%',
  'Bryant': '50%',
  'Chatt': '30%',
  'Colgate': '47%',
  'Colo St': '11%',
  'Connecticut': '9%',
  'Creighton': '17%',
  'CS Fullerton': '51%',
  'Davidson': '13%',
  'Delaware': '44%',
  'Duke': '1%',
  'Georgia St': '47%',
  'Gonzaga': '1%',
  'Houston': '20%',
  'Illinois': '18%',
  'Indiana': '16%',
  'Iowa': '13%',
  'Iowa St': '14%',
  'Jville St': '47%',
  'Kansas': '1%',
  'Kentucky': '1%',
  'Longwood': '49%',
  'Loyola-Chi': '24%',
  'LSU': '9%',
  'Marquette': '16%',
  'Memphis': '8%',
  'Miami FL': '17%',
  'Michigan': '31%',
  'Michigan St': '18%',
  'Montana St': '49%',
  'Murray St': '21%',
  'N Mex St': '33%',
  'Norfolk St': '52%',
  'N Carolina': '32%',
  'Notre Dame': '31%',
  'Ohio St': '20%',
  'Providence': '18%',
  'Purdue': '7%',
  'Richmond': '14%',
  'Rutgers': '14%',
  'S Dakota St': '30%',
  'San Diego St': '7%',
  'San Fran': '15%',
  'Seton Hall': '14%',
  "St Mary's": '12%',
  "St Peter's": '49%'},
 'TCU': {'Tennessee': '25%',
  'Texas': '52%',
  'Texas Tech': '34%',
  'TX Southern': '80%',
  'UAB': '54%',
  'UCLA': '38%',
  'USC': '48%',
  'Vermont': '63%',
  'Villanova': '24%',
  'Virginia Tech': '48%',
  'Wisconsin': '36%',
  'Wright St': '81%',
  'Wyoming': '60%',
  'Yale': '92%',
  'Akron': '66%',
  'Alabama': '39%',
  'Arizona': '36%',
  'Arkansas': '47%',
  'Auburn': '33%',
  'Baylor': '25%',
  'Boise St': '43%',
  'Bryant': '72%',
  'Chatt': '58%',
  'Colgate': '66%',
  'Colo St': '28%',
  'Connecticut': '45%',
  'Creighton': '45%',
  'CS Fullerton': '71%',
  'Davidson': '54%',
  'Delaware': '70%',
  'Duke': '47%',
  'Georgia St': '74%',
  'Gonzaga': '19%',
  'Houston': '47%',
  'Illinois': '27%',
  'Indiana': '53%',
  'Iowa': '54%',
  'Iowa St': '52%',
  'Jville St': '70%',
  'Kansas': '18%',
  'Kentucky': '21%',
  'Longwood': '68%',
  'Loyola-Chi': '46%',
  'LSU': '40%',
  'Marquette': '42%',
  'Memphis': '49%',
  'Miami FL': '55%',
  'Michigan': '52%',
  'Michigan St': '37%',
  'Montana St': '67%',
  'Murray St': '47%',
  'N Mex St': '67%',
  'Norfolk St': '73%',
  'N Carolina': '55%',
  'Notre Dame': '57%',
  'Ohio St': '52%',
  'Providence': '44%',
  'Purdue': '22%',
  'Richmond': '54%',
  'Rutgers': '54%',
  'S Dakota St': '64%',
  'San Diego St': '39%',
  'San Fran': '45%',
  'Seton Hall': '52%',
  "St Mary's": '27%',
  "St Peter's": '75%',
  'TAM C. Christi': '72%'},
 'Tennessee': {'Texas': '87%',
  'Texas Tech': '57%',
  'TX Southern': '99%',
  'UAB': '88%',
  'UCLA': '57%',
  'USC': '85%',
  'Vermont': '82%',
  'Villanova': '47%',
  'Virginia Tech': '83%',
  'Wisconsin': '60%',
  'Wright St': '99%',
  'Wyoming': '94%',
  'Yale': '95%',
  'Akron': '77%',
  'Alabama': '65%',
  'Arizona': '50%',
  'Arkansas': '60%',
  'Auburn': '56%',
  'Baylor': '50%',
  'Boise St': '60%',
  'Bryant': '88%',
  'Chatt': '68%',
  'Colgate': '74%',
  'Colo St': '62%',
  'Connecticut': '63%',
  'Creighton': '68%',
  'CS Fullerton': '80%',
  'Davidson': '62%',
  'Delaware': '79%',
  'Duke': '52%',
  'Georgia St': '92%',
  'Gonzaga': '44%',
  'Houston': '50%',
  'Illinois': '62%',
  'Indiana': '78%',
  'Iowa': '61%',
  'Iowa St': '78%',
  'Jville St': '77%',
  'Kansas': '49%',
  'Kentucky': '49%',
  'Longwood': '79%',
  'Loyola-Chi': '66%',
  'LSU': '66%',
  'Marquette': '70%',
  'Memphis': '68%',
  'Miami FL': '74%',
  'Michigan': '62%',
  'Michigan St': '66%',
  'Montana St': '70%',
  'Murray St': '66%',
  'N Mex St': '75%',
  'Norfolk St': '91%',
  'N Carolina': '64%',
  'Notre Dame': '76%',
  'Ohio St': '70%',
  'Providence': '63%',
  'Purdue': '52%',
  'Richmond': '71%',
  'Rutgers': '73%',
  'S Dakota St': '66%',
  'San Diego St': '68%',
  'San Fran': '63%',
  'Seton Hall': '70%',
  "St Mary's": '49%',
  "St Peter's": '81%',
  'TAM C. Christi': '92%',
  'TCU': '75%'},
 'Texas': {'Texas Tech': '35%',
  'TX Southern': '74%',
  'UAB': '52%',
  'UCLA': '34%',
  'USC': '51%',
  'Vermont': '62%',
  'Villanova': '32%',
  'Virginia Tech': '52%',
  'Wisconsin': '37%',
  'Wright St': '68%',
  'Wyoming': '61%',
  'Yale': '72%',
  'Akron': '67%',
  'Alabama': '48%',
  'Arizona': '35%',
  'Arkansas': '50%',
  'Auburn': '20%',
  'Baylor': '17%',
  'Boise St': '41%',
  'Bryant': '66%',
  'Chatt': '62%',
  'Colgate': '63%',
  'Colo St': '45%',
  'Connecticut': '39%',
  'Creighton': '46%',
  'CS Fullerton': '70%',
  'Davidson': '62%',
  'Delaware': '68%',
  'Duke': '33%',
  'Georgia St': '71%',
  'Gonzaga': '29%',
  'Houston': '41%',
  'Illinois': '40%',
  'Indiana': '55%',
  'Iowa': '50%',
  'Iowa St': '47%',
  'Jville St': '66%',
  'Kansas': '18%',
  'Kentucky': '14%',
  'Longwood': '67%',
  'Loyola-Chi': '56%',
  'LSU': '45%',
  'Marquette': '45%',
  'Memphis': '48%',
  'Miami FL': '56%',
  'Michigan': '53%',
  'Michigan St': '47%',
  'Montana St': '63%',
  'Murray St': '53%',
  'N Mex St': '66%',
  'Norfolk St': '68%',
  'N Carolina': '52%',
  'Notre Dame': '63%',
  'Ohio St': '49%',
  'Providence': '50%',
  'Purdue': '25%',
  'Richmond': '52%',
  'Rutgers': '61%',
  'S Dakota St': '67%',
  'San Diego St': '39%',
  'San Fran': '44%',
  'Seton Hall': '47%',
  "St Mary's": '36%',
  "St Peter's": '74%',
  'TAM C. Christi': '71%',
  'TCU': '48%',
  'Tennessee': '13%'},
 'Texas Tech': {'TX Southern': '99%',
  'UAB': '80%',
  'UCLA': '54%',
  'USC': '78%',
  'Vermont': '81%',
  'Villanova': '49%',
  'Virginia Tech': '80%',
  'Wisconsin': '50%',
  'Wright St': '97%',
  'Wyoming': '87%',
  'Yale': '91%',
  'Akron': '78%',
  'Alabama': '55%',
  'Arizona': '47%',
  'Arkansas': '56%',
  'Auburn': '48%',
  'Baylor': '50%',
  'Boise St': '52%',
  'Bryant': '85%',
  'Chatt': '64%',
  'Colgate': '69%',
  'Colo St': '56%',
  'Connecticut': '49%',
  'Creighton': '56%',
  'CS Fullerton': '77%',
  'Davidson': '60%',
  'Delaware': '73%',
  'Duke': '49%',
  'Georgia St': '84%',
  'Gonzaga': '44%',
  'Houston': '46%',
  'Illinois': '57%',
  'Indiana': '68%',
  'Iowa': '55%',
  'Iowa St': '69%',
  'Jville St': '74%',
  'Kansas': '40%',
  'Kentucky': '45%',
  'Longwood': '75%',
  'Loyola-Chi': '60%',
  'LSU': '54%',
  'Marquette': '55%',
  'Memphis': '59%',
  'Miami FL': '60%',
  'Michigan': '56%',
  'Michigan St': '49%',
  'Montana St': '70%',
  'Murray St': '60%',
  'N Mex St': '67%',
  'Norfolk St': '89%',
  'N Carolina': '61%',
  'Notre Dame': '74%',
  'Ohio St': '60%',
  'Providence': '57%',
  'Purdue': '50%',
  'Richmond': '55%',
  'Rutgers': '67%',
  'S Dakota St': '66%',
  'San Diego St': '49%',
  'San Fran': '51%',
  'Seton Hall': '62%',
  "St Mary's": '49%',
  "St Peter's": '82%',
  'TAM C. Christi': '92%',
  'TCU': '66%',
  'Tennessee': '43%',
  'Texas': '65%'},
 'TX Southern': {'UAB': '30%',
  'UCLA': '22%',
  'USC': '25%',
  'Vermont': '36%',
  'Villanova': '6%',
  'Virginia Tech': '26%',
  'Wisconsin': '13%',
  'Wright St': '38%',
  'Wyoming': '32%',
  'Yale': '46%',
  'Akron': '48%',
  'Alabama': '19%',
  'Arizona': '1%',
  'Arkansas': '19%',
  'Auburn': '1%',
  'Baylor': '1%',
  'Boise St': '10%',
  'Bryant': '45%',
  'Chatt': '36%',
  'Colgate': '51%',
  'Colo St': '21%',
  'Connecticut': '13%',
  'Creighton': '15%',
  'CS Fullerton': '50%',
  'Davidson': '18%',
  'Delaware': '50%',
  'Duke': '1%',
  'Georgia St': '50%',
  'Gonzaga': '1%',
  'Houston': '24%',
  'Illinois': '22%',
  'Indiana': '19%',
  'Iowa': '24%',
  'Iowa St': '14%',
  'Jville St': '50%',
  'Kansas': '1%',
  'Kentucky': '1%',
  'Longwood': '55%',
  'Loyola-Chi': '31%',
  'LSU': '11%',
  'Marquette': '22%',
  'Memphis': '14%',
  'Miami FL': '25%',
  'Michigan': '30%',
  'Michigan St': '17%',
  'Montana St': '52%',
  'Murray St': '26%',
  'N Mex St': '43%',
  'Norfolk St': '58%',
  'N Carolina': '26%',
  'Notre Dame': '32%',
  'Ohio St': '20%',
  'Providence': '19%',
  'Purdue': '9%',
  'Richmond': '25%',
  'Rutgers': '20%',
  'S Dakota St': '36%',
  'San Diego St': '12%',
  'San Fran': '28%',
  'Seton Hall': '21%',
  "St Mary's": '5%',
  "St Peter's": '51%',
  'TAM C. Christi': '60%',
  'TCU': '20%',
  'Tennessee': '1%',
  'Texas': '26%',
  'Texas Tech': '1%'},
 'UAB': {'UCLA': '40%',
  'USC': '43%',
  'Vermont': '52%',
  'Villanova': '30%',
  'Virginia Tech': '43%',
  'Wisconsin': '41%',
  'Wright St': '64%',
  'Wyoming': '49%',
  'Yale': '55%',
  'Akron': '72%',
  'Alabama': '41%',
  'Arizona': '10%',
  'Arkansas': '23%',
  'Auburn': '10%',
  'Baylor': '15%',
  'Boise St': '26%',
  'Bryant': '71%',
  'Chatt': '47%',
  'Colgate': '70%',
  'Colo St': '29%',
  'Connecticut': '30%',
  'Creighton': '43%',
  'CS Fullerton': '74%',
  'Davidson': '37%',
  'Delaware': '67%',
  'Duke': '33%',
  'Georgia St': '73%',
  'Gonzaga': '14%',
  'Houston': '40%',
  'Illinois': '38%',
  'Indiana': '50%',
  'Iowa': '40%',
  'Iowa St': '51%',
  'Jville St': '74%',
  'Kansas': '16%',
  'Kentucky': '19%',
  'Longwood': '74%',
  'Loyola-Chi': '51%',
  'LSU': '40%',
  'Marquette': '40%',
  'Memphis': '39%',
  'Miami FL': '44%',
  'Michigan': '52%',
  'Michigan St': '38%',
  'Montana St': '66%',
  'Murray St': '50%',
  'N Mex St': '59%',
  'Norfolk St': '73%',
  'N Carolina': '47%',
  'Notre Dame': '53%',
  'Ohio St': '50%',
  'Providence': '35%',
  'Purdue': '30%',
  'Richmond': '52%',
  'Rutgers': '49%',
  'S Dakota St': '62%',
  'San Diego St': '40%',
  'San Fran': '52%',
  'Seton Hall': '51%',
  "St Mary's": '35%',
  "St Peter's": '68%',
  'TAM C. Christi': '76%',
  'TCU': '46%',
  'Tennessee': '12%',
  'Texas': '48%',
  'Texas Tech': '20%',
  'TX Southern': '70%'},
 'UCLA': {'USC': '57%',
  'Vermont': '74%',
  'Villanova': '46%',
  'Virginia Tech': '62%',
  'Wisconsin': '50%',
  'Wright St': '87%',
  'Wyoming': '61%',
  'Yale': '91%',
  'Akron': '78%',
  'Alabama': '52%',
  'Arizona': '34%',
  'Arkansas': '55%',
  'Auburn': '48%',
  'Baylor': '34%',
  'Boise St': '52%',
  'Bryant': '75%',
  'Chatt': '60%',
  'Colgate': '74%',
  'Colo St': '53%',
  'Connecticut': '49%',
  'Creighton': '56%',
  'CS Fullerton': '81%',
  'Davidson': '61%',
  'Delaware': '79%',
  'Duke': '47%',
  'Georgia St': '79%',
  'Gonzaga': '33%',
  'Houston': '48%',
  'Illinois': '60%',
  'Indiana': '72%',
  'Iowa': '57%',
  'Iowa St': '67%',
  'Jville St': '78%',
  'Kansas': '21%',
  'Kentucky': '41%',
  'Longwood': '79%',
  'Loyola-Chi': '62%',
  'LSU': '61%',
  'Marquette': '57%',
  'Memphis': '62%',
  'Miami FL': '64%',
  'Michigan': '57%',
  'Michigan St': '53%',
  'Montana St': '74%',
  'Murray St': '58%',
  'N Mex St': '65%',
  'Norfolk St': '79%',
  'N Carolina': '63%',
  'Notre Dame': '73%',
  'Ohio St': '69%',
  'Providence': '57%',
  'Purdue': '50%',
  'Richmond': '62%',
  'Rutgers': '64%',
  'S Dakota St': '67%',
  'San Diego St': '51%',
  'San Fran': '54%',
  'Seton Hall': '64%',
  "St Mary's": '44%',
  "St Peter's": '79%',
  'TAM C. Christi': '79%',
  'TCU': '62%',
  'Tennessee': '43%',
  'Texas': '66%',
  'Texas Tech': '46%',
  'TX Southern': '78%',
  'UAB': '60%'},
 'USC': {'Vermont': '68%',
  'Villanova': '34%',
  'Virginia Tech': '45%',
  'Wisconsin': '43%',
  'Wright St': '76%',
  'Wyoming': '68%',
  'Yale': '78%',
  'Akron': '74%',
  'Alabama': '45%',
  'Arizona': '15%',
  'Arkansas': '28%',
  'Auburn': '20%',
  'Baylor': '23%',
  'Boise St': '33%',
  'Bryant': '74%',
  'Chatt': '54%',
  'Colgate': '72%',
  'Colo St': '36%',
  'Connecticut': '45%',
  'Creighton': '53%',
  'CS Fullerton': '74%',
  'Davidson': '51%',
  'Delaware': '72%',
  'Duke': '35%',
  'Georgia St': '71%',
  'Gonzaga': '15%',
  'Houston': '46%',
  'Illinois': '34%',
  'Indiana': '53%',
  'Iowa': '47%',
  'Iowa St': '53%',
  'Jville St': '74%',
  'Kansas': '15%',
  'Kentucky': '20%',
  'Longwood': '72%',
  'Loyola-Chi': '55%',
  'LSU': '52%',
  'Marquette': '50%',
  'Memphis': '45%',
  'Miami FL': '51%',
  'Michigan': '48%',
  'Michigan St': '48%',
  'Montana St': '71%',
  'Murray St': '53%',
  'N Mex St': '64%',
  'Norfolk St': '77%',
  'N Carolina': '49%',
  'Notre Dame': '60%',
  'Ohio St': '49%',
  'Providence': '27%',
  'Purdue': '27%',
  'Richmond': '52%',
  'Rutgers': '51%',
  'S Dakota St': '64%',
  'San Diego St': '46%',
  'San Fran': '45%',
  'Seton Hall': '47%',
  "St Mary's": '46%',
  "St Peter's": '73%',
  'TAM C. Christi': '75%',
  'TCU': '52%',
  'Tennessee': '15%',
  'Texas': '49%',
  'Texas Tech': '22%',
  'TX Southern': '75%',
  'UAB': '57%',
  'UCLA': '43%'},
 'Vermont': {'Villanova': '33%',
  'Virginia Tech': '36%',
  'Wisconsin': '39%',
  'Wright St': '66%',
  'Wyoming': '51%',
  'Yale': '50%',
  'Akron': '59%',
  'Alabama': '38%',
  'Arizona': '16%',
  'Arkansas': '28%',
  'Auburn': '25%',
  'Baylor': '21%',
  'Boise St': '17%',
  'Bryant': '69%',
  'Chatt': '48%',
  'Colgate': '69%',
  'Colo St': '29%',
  'Connecticut': '33%',
  'Creighton': '43%',
  'CS Fullerton': '59%',
  'Davidson': '28%',
  'Delaware': '58%',
  'Duke': '25%',
  'Georgia St': '57%',
  'Gonzaga': '23%',
  'Houston': '38%',
  'Illinois': '36%',
  'Indiana': '46%',
  'Iowa': '31%',
  'Iowa St': '45%',
  'Jville St': '67%',
  'Kansas': '27%',
  'Kentucky': '25%',
  'Longwood': '65%',
  'Loyola-Chi': '51%',
  'LSU': '31%',
  'Marquette': '28%',
  'Memphis': '39%',
  'Miami FL': '43%',
  'Michigan': '45%',
  'Michigan St': '33%',
  'Montana St': '57%',
  'Murray St': '47%',
  'N Mex St': '57%',
  'Norfolk St': '72%',
  'N Carolina': '44%',
  'Notre Dame': '50%',
  'Ohio St': '34%',
  'Providence': '33%',
  'Purdue': '26%',
  'Richmond': '50%',
  'Rutgers': '45%',
  'S Dakota St': '54%',
  'San Diego St': '33%',
  'San Fran': '42%',
  'Seton Hall': '40%',
  "St Mary's": '29%',
  "St Peter's": '60%',
  'TAM C. Christi': '68%',
  'TCU': '37%',
  'Tennessee': '18%',
  'Texas': '38%',
  'Texas Tech': '19%',
  'TX Southern': '64%',
  'UAB': '48%',
  'UCLA': '26%',
  'USC': '32%'},
 'Villanova': {'Virginia Tech': '82%',
  'Wisconsin': '61%',
  'Wright St': '99%',
  'Wyoming': '92%',
  'Yale': '92%',
  'Akron': '79%',
  'Alabama': '64%',
  'Arizona': '50%',
  'Arkansas': '62%',
  'Auburn': '54%',
  'Baylor': '48%',
  'Boise St': '63%',
  'Bryant': '94%',
  'Chatt': '68%',
  'Colgate': '70%',
  'Colo St': '60%',
  'Connecticut': '63%',
  'Creighton': '71%',
  'CS Fullerton': '92%',
  'Davidson': '68%',
  'Delaware': '90%',
  'Duke': '52%',
  'Georgia St': '94%',
  'Gonzaga': '39%',
  'Houston': '50%',
  'Illinois': '67%',
  'Indiana': '76%',
  'Iowa': '55%',
  'Iowa St': '76%',
  'Jville St': '90%',
  'Kansas': '52%',
  'Kentucky': '44%',
  'Longwood': '77%',
  'Loyola-Chi': '67%',
  'LSU': '62%',
  'Marquette': '64%',
  'Memphis': '71%',
  'Miami FL': '76%',
  'Michigan': '64%',
  'Michigan St': '61%',
  'Montana St': '76%',
  'Murray St': '66%',
  'N Mex St': '77%',
  'Norfolk St': '95%',
  'N Carolina': '66%',
  'Notre Dame': '80%',
  'Ohio St': '71%',
  'Providence': '63%',
  'Purdue': '57%',
  'Richmond': '74%',
  'Rutgers': '67%',
  'S Dakota St': '67%',
  'San Diego St': '66%',
  'San Fran': '66%',
  'Seton Hall': '73%',
  "St Mary's": '53%',
  "St Peter's": '91%',
  'TAM C. Christi': '95%',
  'TCU': '76%',
  'Tennessee': '53%',
  'Texas': '68%',
  'Texas Tech': '51%',
  'TX Southern': '94%',
  'UAB': '70%',
  'UCLA': '54%',
  'USC': '66%',
  'Vermont': '67%'},
 'Virginia Tech': {'Wisconsin': '42%',
  'Wright St': '89%',
  'Wyoming': '54%',
  'Yale': '89%',
  'Akron': '71%',
  'Alabama': '41%',
  'Arizona': '20%',
  'Arkansas': '31%',
  'Auburn': '28%',
  'Baylor': '24%',
  'Boise St': '12%',
  'Bryant': '68%',
  'Chatt': '63%',
  'Colgate': '69%',
  'Colo St': '24%',
  'Connecticut': '36%',
  'Creighton': '48%',
  'CS Fullerton': '71%',
  'Davidson': '60%',
  'Delaware': '70%',
  'Duke': '37%',
  'Georgia St': '74%',
  'Gonzaga': '22%',
  'Houston': '40%',
  'Illinois': '35%',
  'Indiana': '54%',
  'Iowa': '42%',
  'Iowa St': '63%',
  'Jville St': '73%',
  'Kansas': '20%',
  'Kentucky': '21%',
  'Longwood': '70%',
  'Loyola-Chi': '62%',
  'LSU': '49%',
  'Marquette': '50%',
  'Memphis': '50%',
  'Miami FL': '57%',
  'Michigan': '56%',
  'Michigan St': '36%',
  'Montana St': '68%',
  'Murray St': '56%',
  'N Mex St': '67%',
  'Norfolk St': '72%',
  'N Carolina': '45%',
  'Notre Dame': '58%',
  'Ohio St': '42%',
  'Providence': '29%',
  'Purdue': '26%',
  'Richmond': '55%',
  'Rutgers': '58%',
  'S Dakota St': '64%',
  'San Diego St': '33%',
  'San Fran': '47%',
  'Seton Hall': '47%',
  "St Mary's": '39%',
  "St Peter's": '75%',
  'TAM C. Christi': '72%',
  'TCU': '52%',
  'Tennessee': '17%',
  'Texas': '48%',
  'Texas Tech': '20%',
  'TX Southern': '74%',
  'UAB': '57%',
  'UCLA': '38%',
  'USC': '55%',
  'Vermont': '64%',
  'Villanova': '18%'},
 'Wisconsin': {'Wright St': '99%',
  'Wyoming': '80%',
  'Yale': '89%',
  'Akron': '72%',
  'Alabama': '50%',
  'Arizona': '47%',
  'Arkansas': '51%',
  'Auburn': '51%',
  'Baylor': '47%',
  'Boise St': '45%',
  'Bryant': '86%',
  'Chatt': '62%',
  'Colgate': '68%',
  'Colo St': '56%',
  'Connecticut': '47%',
  'Creighton': '53%',
  'CS Fullerton': '78%',
  'Davidson': '60%',
  'Delaware': '76%',
  'Duke': '50%',
  'Georgia St': '86%',
  'Gonzaga': '37%',
  'Houston': '48%',
  'Illinois': '47%',
  'Indiana': '68%',
  'Iowa': '50%',
  'Iowa St': '66%',
  'Jville St': '77%',
  'Kansas': '43%',
  'Kentucky': '47%',
  'Longwood': '73%',
  'Loyola-Chi': '51%',
  'LSU': '51%',
  'Marquette': '60%',
  'Memphis': '58%',
  'Miami FL': '66%',
  'Michigan': '53%',
  'Michigan St': '46%',
  'Montana St': '72%',
  'Murray St': '49%',
  'N Mex St': '67%',
  'Norfolk St': '91%',
  'N Carolina': '57%',
  'Notre Dame': '74%',
  'Ohio St': '59%',
  'Providence': '59%',
  'Purdue': '44%',
  'Richmond': '59%',
  'Rutgers': '67%',
  'S Dakota St': '65%',
  'San Diego St': '49%',
  'San Fran': '50%',
  'Seton Hall': '65%',
  "St Mary's": '44%',
  "St Peter's": '80%',
  'TAM C. Christi': '90%',
  'TCU': '64%',
  'Tennessee': '40%',
  'Texas': '63%',
  'Texas Tech': '50%',
  'TX Southern': '87%',
  'UAB': '59%',
  'UCLA': '50%',
  'USC': '57%',
  'Vermont': '61%',
  'Villanova': '39%',
  'Virginia Tech': '58%'},
 'Wright St': {'Wyoming': '29%',
  'Yale': '43%',
  'Akron': '48%',
  'Alabama': '18%',
  'Arizona': '1%',
  'Arkansas': '16%',
  'Auburn': '1%',
  'Baylor': '1%',
  'Boise St': '9%',
  'Bryant': '61%',
  'Chatt': '36%',
  'Colgate': '55%',
  'Colo St': '10%',
  'Connecticut': '14%',
  'Creighton': '11%',
  'CS Fullerton': '51%',
  'Davidson': '15%',
  'Delaware': '52%',
  'Duke': '1%',
  'Georgia St': '56%',
  'Gonzaga': '1%',
  'Houston': '24%',
  'Illinois': '10%',
  'Indiana': '23%',
  'Iowa': '19%',
  'Iowa St': '19%',
  'Jville St': '61%',
  'Kansas': '1%',
  'Kentucky': '1%',
  'Longwood': '60%',
  'Loyola-Chi': '35%',
  'LSU': '17%',
  'Marquette': '16%',
  'Memphis': '11%',
  'Miami FL': '14%',
  'Michigan': '25%',
  'Michigan St': '10%',
  'Montana St': '54%',
  'Murray St': '32%',
  'N Mex St': '45%',
  'Norfolk St': '62%',
  'N Carolina': '32%',
  'Notre Dame': '35%',
  'Ohio St': '18%',
  'Providence': '15%',
  'Purdue': '3%',
  'Richmond': '19%',
  'Rutgers': '19%',
  'S Dakota St': '40%',
  'San Diego St': '12%',
  'San Fran': '21%',
  'Seton Hall': '28%',
  "St Mary's": '9%',
  "St Peter's": '58%',
  'TAM C. Christi': '65%',
  'TCU': '19%',
  'Tennessee': '1%',
  'Texas': '32%',
  'Texas Tech': '3%',
  'TX Southern': '62%',
  'UAB': '36%',
  'UCLA': '13%',
  'USC': '24%',
  'Vermont': '34%',
  'Villanova': '1%',
  'Virginia Tech': '11%',
  'Wisconsin': '1%'},
 'Wyoming': {'Yale': '57%',
  'Akron': '65%',
  'Alabama': '29%',
  'Arizona': '18%',
  'Arkansas': '20%',
  'Auburn': '15%',
  'Baylor': '13%',
  'Boise St': '10%',
  'Bryant': '62%',
  'Chatt': '49%',
  'Colgate': '62%',
  'Colo St': '15%',
  'Connecticut': '25%',
  'Creighton': '22%',
  'CS Fullerton': '72%',
  'Davidson': '43%',
  'Delaware': '67%',
  'Duke': '38%',
  'Georgia St': '70%',
  'Gonzaga': '10%',
  'Houston': '35%',
  'Illinois': '15%',
  'Indiana': '43%',
  'Iowa': '35%',
  'Iowa St': '43%',
  'Jville St': '68%',
  'Kansas': '10%',
  'Kentucky': '9%',
  'Longwood': '66%',
  'Loyola-Chi': '53%',
  'LSU': '29%',
  'Marquette': '26%',
  'Memphis': '24%',
  'Miami FL': '44%',
  'Michigan': '47%',
  'Michigan St': '22%',
  'Montana St': '71%',
  'Murray St': '47%',
  'N Mex St': '56%',
  'Norfolk St': '72%',
  'N Carolina': '34%',
  'Notre Dame': '53%',
  'Ohio St': '30%',
  'Providence': '25%',
  'Purdue': '20%',
  'Richmond': '41%',
  'Rutgers': '50%',
  'S Dakota St': '53%',
  'San Diego St': '23%',
  'San Fran': '48%',
  'Seton Hall': '34%',
  "St Mary's": '29%',
  "St Peter's": '72%',
  'TAM C. Christi': '75%',
  'TCU': '40%',
  'Tennessee': '6%',
  'Texas': '39%',
  'Texas Tech': '13%',
  'TX Southern': '68%',
  'UAB': '51%',
  'UCLA': '39%',
  'USC': '32%',
  'Vermont': '49%',
  'Villanova': '8%',
  'Virginia Tech': '46%',
  'Wisconsin': '20%',
  'Wright St': '71%'},
 'Yale': {'Akron': '50%',
  'Alabama': '19%',
  'Arizona': '1%',
  'Arkansas': '12%',
  'Auburn': '6%',
  'Baylor': '1%',
  'Boise St': '9%',
  'Bryant': '58%',
  'Chatt': '43%',
  'Colgate': '41%',
  'Colo St': '11%',
  'Connecticut': '14%',
  'Creighton': '12%',
  'CS Fullerton': '58%',
  'Davidson': '17%',
  'Delaware': '47%',
  'Duke': '9%',
  'Georgia St': '62%',
  'Gonzaga': '1%',
  'Houston': '28%',
  'Illinois': '13%',
  'Indiana': '34%',
  'Iowa': '14%',
  'Iowa St': '9%',
  'Jville St': '48%',
  'Kansas': '1%',
  'Kentucky': '7%',
  'Longwood': '50%',
  'Loyola-Chi': '39%',
  'LSU': '14%',
  'Marquette': '12%',
  'Memphis': '10%',
  'Miami FL': '16%',
  'Michigan': '22%',
  'Michigan St': '7%',
  'Montana St': '54%',
  'Murray St': '37%',
  'N Mex St': '45%',
  'Norfolk St': '54%',
  'N Carolina': '30%',
  'Notre Dame': '27%',
  'Ohio St': '17%',
  'Providence': '13%',
  'Purdue': '15%',
  'Richmond': '35%',
  'Rutgers': '4%',
  'S Dakota St': '56%',
  'San Diego St': '11%',
  'San Fran': '19%',
  'Seton Hall': '19%',
  "St Mary's": '10%',
  "St Peter's": '58%',
  'TAM C. Christi': '66%',
  'TCU': '8%',
  'Tennessee': '5%',
  'Texas': '28%',
  'Texas Tech': '9%',
  'TX Southern': '54%',
  'UAB': '45%',
  'UCLA': '9%',
  'USC': '22%',
  'Vermont': '50%',
  'Villanova': '8%',
  'Virginia Tech': '11%',
  'Wisconsin': '11%',
  'Wright St': '57%',
  'Wyoming': '43%'}}